-- Corrective E2 serving-role hardening after prerequisite review (Decision #123).
-- DELTA-FREE `--custom` migration under Decision #122/C14: drizzle-kit cannot
-- emit cluster-role attributes, membership reconciliation, ACL resets, or RLS
-- policy transitions. The custom stub was generated by drizzle-kit, then this
-- idempotent security DDL was appended from the authoritative builder below.
-- Applied migration 0213 is intentionally unchanged. Re-application converges
-- direct grants/memberships/attributes; ownership drift raises and stops closed.
-- Generated from server/src/db/rls-tenant.ts; keep this file byte-for-byte aligned.
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles role WHERE role.rolname = 'aoa_app' AND (EXISTS (SELECT 1 FROM pg_database database WHERE database.datdba = role.oid AND database.datname = current_database()) OR EXISTS (SELECT 1 FROM pg_namespace namespace WHERE namespace.nspowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%') OR EXISTS (SELECT 1 FROM pg_class relation JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace WHERE relation.relowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%') OR EXISTS (SELECT 1 FROM pg_proc function JOIN pg_namespace namespace ON namespace.oid = function.pronamespace WHERE function.proowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%') OR EXISTS (SELECT 1 FROM pg_type type JOIN pg_namespace namespace ON namespace.oid = type.typnamespace WHERE type.typowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%'))) THEN RAISE EXCEPTION 'Serving role aoa_app owns an application object'; END IF; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DO $$ DECLARE inherited_role record; BEGIN FOR inherited_role IN SELECT parent.rolname AS role_name FROM pg_auth_members membership JOIN pg_roles member ON member.oid = membership.member JOIN pg_roles parent ON parent.oid = membership.roleid WHERE member.rolname = 'aoa_app' LOOP EXECUTE format('REVOKE %I FROM %I', inherited_role.role_name, 'aoa_app'); END LOOP; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
ALTER ROLE "aoa_app" NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT USAGE ON SCHEMA public TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles role WHERE role.rolname = 'aoa_operator' AND (EXISTS (SELECT 1 FROM pg_database database WHERE database.datdba = role.oid AND database.datname = current_database()) OR EXISTS (SELECT 1 FROM pg_namespace namespace WHERE namespace.nspowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%') OR EXISTS (SELECT 1 FROM pg_class relation JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace WHERE relation.relowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%') OR EXISTS (SELECT 1 FROM pg_proc function JOIN pg_namespace namespace ON namespace.oid = function.pronamespace WHERE function.proowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%') OR EXISTS (SELECT 1 FROM pg_type type JOIN pg_namespace namespace ON namespace.oid = type.typnamespace WHERE type.typowner = role.oid AND namespace.nspname <> 'information_schema' AND namespace.nspname NOT LIKE 'pg_%'))) THEN RAISE EXCEPTION 'Serving role aoa_operator owns an application object'; END IF; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DO $$ DECLARE inherited_role record; BEGIN FOR inherited_role IN SELECT parent.rolname AS role_name FROM pg_auth_members membership JOIN pg_roles member ON member.oid = membership.member JOIN pg_roles parent ON parent.oid = membership.roleid WHERE member.rolname = 'aoa_operator' LOOP EXECUTE format('REVOKE %I FROM %I', inherited_role.role_name, 'aoa_operator'); END LOOP; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
ALTER ROLE "aoa_operator" NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT USAGE ON SCHEMA public TO "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "jobs" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "job_attempts" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "leases" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "workers" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "services" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "service_instances" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "job_artifacts" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "job_secret_handles" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, UPDATE ON "issues" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, UPDATE ON "agents" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "task_dependencies" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "issue_labels" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "labels" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "notifications" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "user_roles" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "company_memberships" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "notification_preferences" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT ON "notification_digest_items" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, UPDATE ON "hub_counter_snapshots" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT INSERT ON "hub_audit" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "heartbeat_runs" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "agent_wakeup_requests" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, UPDATE ON "discussion_entries" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "internal_agent_runs" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, UPDATE ON "thread_orchestration_state" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "internal_agent_conversations" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "internal_agent_messages" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "internal_agent_config" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, UPDATE ON "companies" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "organizations" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "approvals" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "agent_runtime_decisions" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "agent_runtime_trust_rules" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "internal_agent_runtime_approvals" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "internal_agent_tool_trust_rules" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE, DELETE ON "budget_policies" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "budget_incidents" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT ON "cost_events" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT ON "activity_log" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "projects" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT, INSERT, UPDATE ON "task_outputs" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT INSERT ON "issue_comments" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "artifacts" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "artifact_versions" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "assets" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "execution_workspaces" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ON "workspace_runtime_services" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ("id", "scope", "organization_id", "label", "status", "created_at", "updated_at") ON "workers" TO "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
GRANT SELECT ("id", "organization_id", "slug", "kind", "trust_class", "status", "capabilities", "last_seen_at", "created_at", "updated_at") ON "execution_targets" TO "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
ALTER TABLE "execution_targets" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
ALTER TABLE "execution_targets" NO FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DROP POLICY IF EXISTS "execution_targets_tenant_serving" ON "execution_targets";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
CREATE POLICY "execution_targets_tenant_serving" ON "execution_targets" FOR SELECT TO "aoa_app"
  USING (organization_id IS NULL OR organization_id = current_setting('aoa.organization_id', true)::uuid);
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DROP POLICY IF EXISTS "workers_platform_operator" ON "workers";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
CREATE POLICY "workers_platform_operator" ON "workers" TO "aoa_operator"
  USING (organization_id IS NULL AND scope = 'platform')
  WITH CHECK (organization_id IS NULL AND scope = 'platform');
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
DROP POLICY IF EXISTS "execution_targets_platform_operator" ON "execution_targets";
--> statement-breakpoint
-- C14 hand-authored security DDL: drizzle-kit cannot emit this statement; its convergent assertion/revoke/grant/drop-before-create form is idempotent.
CREATE POLICY "execution_targets_platform_operator" ON "execution_targets" TO "aoa_operator"
  USING (organization_id IS NULL AND owner_user_id IS NULL)
  WITH CHECK (organization_id IS NULL AND owner_user_id IS NULL);
