-- DEP-003 (E6 deployment harness): additive operator-gated 0188 cutover marker table.
-- Generated by `drizzle-kit generate`; the C14 idempotency guards (`IF NOT EXISTS`)
-- were hand-appended after generation so a partial-apply replay is a no-op (repo
-- convention, enforced by migration-idempotency.test.ts). Schema DDL is NOT
-- hand-authored — only the idempotency guards are. The RLS/GRANT/POLICY security
-- DDL lives in the sibling custom migration 0233_distributed_cutover_marker_rls.sql.
CREATE TABLE IF NOT EXISTS "distributed_cutover_markers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"candidate_sha" text NOT NULL,
	"snapshot_ref" text NOT NULL,
	"snapshot_checksum" text NOT NULL,
	"verified_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "distributed_cutover_markers_candidate_sha_uq" ON "distributed_cutover_markers" USING btree ("candidate_sha");
