-- DAT-006 (E5 workspaces): reconcile local workspaces + orphan output. Generated by
-- `drizzle-kit generate`; the C14 idempotency guards (`IF NOT EXISTS` on CREATE
-- TABLE/INDEX + ADD COLUMN, and `DO $$ … duplicate_object` on ADD CONSTRAINT) were
-- hand-appended after generation so a partial-apply replay is a no-op (repo convention,
-- enforced by migration-idempotency.test.ts). Schema DDL is NOT hand-authored — only the
-- idempotency guards are.
--   * NEW `folder_grants` table — the durable owner×execution-target×declared-base grant
--     the frozen `snapshotProvenance.folderGrantId` resolves to (TEN-006 per-table RLS).
--     Its RLS/GRANT/POLICY security DDL lives in the sibling custom migration
--     0253_folder_grants_rls.sql.
--   * WIDEN `job_artifacts` with 4 nullable additive orphan/quarantine columns; the
--     orphan row carries `status='quarantined'`. It inherits the whole-table aoa_app
--     grant + FORCE RLS + tenant-isolation policy (0211) — no keystone reconciliation.
CREATE TABLE IF NOT EXISTS "folder_grants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"owner_user_id" text NOT NULL,
	"execution_target_id" uuid NOT NULL,
	"target_authority_key" text NOT NULL,
	"device_generation" integer DEFAULT 1 NOT NULL,
	"folder_grant_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"declared_base_path" text NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "folder_grants_owner_authority_check" CHECK (target_authority_key = 'owner:' || organization_id::text || ':' || owner_user_id)
);
--> statement-breakpoint
ALTER TABLE "job_artifacts" ADD COLUMN IF NOT EXISTS "orphan_disposition" text;--> statement-breakpoint
ALTER TABLE "job_artifacts" ADD COLUMN IF NOT EXISTS "quarantine_reason" text;--> statement-breakpoint
ALTER TABLE "job_artifacts" ADD COLUMN IF NOT EXISTS "observed_lease_id" uuid;--> statement-breakpoint
ALTER TABLE "job_artifacts" ADD COLUMN IF NOT EXISTS "observed_fence_token" text;--> statement-breakpoint
-- C14 idempotency guard: ADD CONSTRAINT is not IF-NOT-EXISTS-able; wrap for replay.
DO $$ BEGIN
 ALTER TABLE "folder_grants" ADD CONSTRAINT "folder_grants_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "folder_grants" ADD CONSTRAINT "folder_grants_target_authority_fk" FOREIGN KEY ("target_authority_key","execution_target_id") REFERENCES "public"."execution_targets"("target_authority_key","id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "folder_grants" ADD CONSTRAINT "folder_grants_owner_user_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "folder_grants_organization_idx" ON "folder_grants" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "folder_grants_target_idx" ON "folder_grants" USING btree ("execution_target_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "folder_grants_folder_grant_id_uq" ON "folder_grants" USING btree ("folder_grant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "folder_grants_active_base_uq" ON "folder_grants" USING btree ("organization_id","execution_target_id","owner_user_id","declared_base_path") WHERE revoked_at IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "job_artifacts_quarantined_identity_uidx" ON "job_artifacts" USING btree ("organization_id","job_id","attempt","identifier") WHERE status = 'quarantined';