-- DEP-009 (E6 two-replica shared admission): NEW `worker_admission_rate_limits`
-- table — the shared per-(organization, window_start) fixed-window admission counter
-- both control-plane replicas increment. Generated by `drizzle-kit generate`; the C14
-- idempotency guards (`IF NOT EXISTS` on CREATE TABLE, and `DO $$ … duplicate_object`
-- on ADD CONSTRAINT) were hand-appended after generation so a partial-apply replay is a
-- no-op (repo convention, enforced by migration-idempotency.test.ts). Schema DDL is NOT
-- hand-authored — only the idempotency guards are. Its RLS/GRANT/POLICY security DDL
-- lives in the sibling custom migration 0255_worker_admission_rate_limit_rls.sql.
CREATE TABLE IF NOT EXISTS "worker_admission_rate_limits" (
	"organization_id" uuid NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"request_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "worker_admission_rate_limits_pkey" PRIMARY KEY("organization_id","window_start")
);
--> statement-breakpoint
-- C14 idempotency guard: ADD CONSTRAINT is not IF-NOT-EXISTS-able; wrap for replay.
DO $$ BEGIN
 ALTER TABLE "worker_admission_rate_limits" ADD CONSTRAINT "worker_admission_rate_limits_org_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
