-- Generated by `drizzle-kit generate`; the C14 idempotency guards (`IF NOT EXISTS` on
-- CREATE TABLE/INDEX; `DO $$ … EXCEPTION WHEN duplicate_object` on each ADD CONSTRAINT)
-- were hand-appended after generation so a partial-apply replay is a no-op (repo
-- convention, enforced by migration-idempotency.test.ts + migration-readiness). Schema
-- DDL is NOT hand-authored — only the idempotency guards are. The RLS/GRANT/POLICY
-- security DDL is the hand-appended block below.
CREATE TABLE IF NOT EXISTS "legacy_resource_reconciliation" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"environment_lease_id" uuid,
	"environment_id" uuid,
	"resource_key" text NOT NULL,
	"resource_type" text NOT NULL,
	"legacy_status" text,
	"provider" text,
	"provider_lease_id" text,
	"disposition" text NOT NULL,
	"resource_labels_hash" text,
	"key_generation" text,
	"cleanup_outcome" text,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "legacy_resource_reconciliation" ADD CONSTRAINT "legacy_resource_reconciliation_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "legacy_resource_reconciliation" ADD CONSTRAINT "legacy_resource_reconciliation_environment_lease_id_environment_leases_id_fk" FOREIGN KEY ("environment_lease_id") REFERENCES "public"."environment_leases"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "legacy_resource_reconciliation" ADD CONSTRAINT "legacy_resource_reconciliation_environment_id_environments_id_fk" FOREIGN KEY ("environment_id") REFERENCES "public"."environments"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "legacy_resource_reconciliation_company_resource_key_uq" ON "legacy_resource_reconciliation" USING btree ("company_id","resource_key");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "legacy_resource_reconciliation_company_idx" ON "legacy_resource_reconciliation" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "legacy_resource_reconciliation_disposition_idx" ON "legacy_resource_reconciliation" USING btree ("disposition");
-- MIG-008 (E10 desktop-migration) Decision #122 / C14 custom security DDL for the
-- append-only legacy-lease/resource reconciliation crosswalk (slug
-- `legacy_resource_reconciliation`). drizzle-kit cannot express roles, operation
-- grants, FORCE RLS, or policies, so this entire block is hand-APPENDED to the
-- generated CREATE TABLE above. Every statement is naturally idempotent or
-- guarded/drop-before-create per C14, so a re-apply under the migration advisory
-- lock is a no-op.
--
-- Security matrix (mirrors the DEP-003 cutover marker 0233 operator-metadata shape):
--   * aoa_operator  WRITE      — only the operator-authored reconciliation pass
--                                (via the aoa_operator non-owner pool) writes rows.
--   * aoa_app       READ-ONLY  — the control plane reads the closure store OUTSIDE
--                                a tenant transaction (policy: aoa.organization_id unset).
--   * tenants       NONE       — an aoa_app query WITH the tenant GUC set never
--                                matches the read policy, so the crosswalk is invisible.
--   * FORCE RLS                — defense-in-depth against a non-superuser owner
--                                mistake (E2-F004 rationale).
-- The crosswalk is company-scoped DATA (company_id) but operator-metadata INFRA for
-- RLS (keyed like the platform cutover marker, not the tenant GUC).
-- C14 hand-authored security DDL: guarded operator role creation.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aoa_operator') THEN CREATE ROLE "aoa_operator" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE; END IF; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: guarded serving role creation.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aoa_app') THEN CREATE ROLE "aoa_app" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE; END IF; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: remove ambient public authority first.
REVOKE ALL ON "legacy_resource_reconciliation" FROM PUBLIC;
--> statement-breakpoint
-- C14 hand-authored security DDL: strip any inherited aoa_app authority before the narrow re-grant.
REVOKE ALL ON "legacy_resource_reconciliation" FROM "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: strip any inherited aoa_operator authority before the narrow re-grant.
REVOKE ALL ON "legacy_resource_reconciliation" FROM "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: operator writes durable reconciliation records (no DELETE — records are durable).
GRANT SELECT, INSERT, UPDATE ON "legacy_resource_reconciliation" TO "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: the control plane reads the closure store; it never writes it.
GRANT SELECT ON "legacy_resource_reconciliation" TO "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: natural idempotent RLS enablement.
ALTER TABLE "legacy_resource_reconciliation" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
-- C14 hand-authored security DDL: FORCE removes a non-superuser owner's exemption.
ALTER TABLE "legacy_resource_reconciliation" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
-- C14 hand-authored security DDL: drop-before-create operator write policy (idempotent replay guard).
DROP POLICY IF EXISTS "legacy_resource_reconciliation_operator_write" ON "legacy_resource_reconciliation";
--> statement-breakpoint
-- C14 hand-authored security DDL: aoa_operator has full access to this operator-metadata table.
CREATE POLICY "legacy_resource_reconciliation_operator_write" ON "legacy_resource_reconciliation" TO "aoa_operator"
  USING (true)
  WITH CHECK (true);
--> statement-breakpoint
-- C14 hand-authored security DDL: drop-before-create app read policy (idempotent replay guard).
DROP POLICY IF EXISTS "legacy_resource_reconciliation_app_read" ON "legacy_resource_reconciliation";
--> statement-breakpoint
-- C14 hand-authored security DDL: aoa_app may READ the crosswalk ONLY outside a tenant transaction;
-- a tenant GUC (aoa.organization_id) being set makes the crosswalk invisible (tenants NONE).
CREATE POLICY "legacy_resource_reconciliation_app_read" ON "legacy_resource_reconciliation" FOR SELECT TO "aoa_app"
  USING (current_setting('aoa.organization_id', true) IS NULL);
