-- CLI-006 (E7 gate): the durable execution-ownership marker on heartbeat_runs.
-- Generated by `drizzle-kit generate`; the C14 idempotency guards (`IF NOT EXISTS`
-- on ADD COLUMN) were hand-appended after generation so a partial-apply replay is a
-- no-op (repo convention, enforced by migration-idempotency.test.ts). Schema DDL is
-- NOT hand-authored — only the idempotency guards are.
--
--   * `execution_owner` — null on every legacy run (this process's adapter is the
--     executor); 'distributed' when a worker attempt owns execution and the
--     heartbeat has suppressed its own `adapter.execute`. Durable rather than
--     in-process because `reapOrphanedRuns` exempts a run only when it appears in
--     the in-process `runningProcesses` map, which a distributed attempt never
--     populates, and the startup reap runs with `staleThresholdMs = 0`.
--   * `distributed_job_id` / `distributed_attempt_id` — bind the run to its
--     distributed evidence. Not recoverable by idempotency-key lookup, because
--     CLI-005's active convert reuses the same `run.id` key for runs the legacy
--     adapter still executes.
--
-- All three are nullable and additive: every existing row reads as a legacy run,
-- and no backfill is required.
ALTER TABLE "heartbeat_runs" ADD COLUMN IF NOT EXISTS "execution_owner" text;--> statement-breakpoint
ALTER TABLE "heartbeat_runs" ADD COLUMN IF NOT EXISTS "distributed_job_id" uuid;--> statement-breakpoint
ALTER TABLE "heartbeat_runs" ADD COLUMN IF NOT EXISTS "distributed_attempt_id" uuid;
