-- Generated by `drizzle-kit generate`; the C14 idempotency guards (`IF NOT EXISTS` on
-- CREATE TABLE/INDEX; `DO $$ … EXCEPTION WHEN duplicate_object` on each ADD CONSTRAINT)
-- were hand-appended after generation so a partial-apply replay is a no-op (repo
-- convention, enforced by migration-idempotency.test.ts + migration-readiness). Schema
-- DDL is NOT hand-authored — only the idempotency guards are. The RLS/GRANT/POLICY
-- security DDL is the hand-appended block below.
CREATE TABLE IF NOT EXISTS "legacy_reconciliation_passes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pass_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"company_id" uuid NOT NULL,
	"snapshot_at" timestamp with time zone NOT NULL,
	"key_generation" text NOT NULL,
	"completed_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "legacy_reconciliation_passes" ADD CONSTRAINT "legacy_reconciliation_passes_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "legacy_reconciliation_passes" ADD CONSTRAINT "legacy_reconciliation_passes_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "legacy_reconciliation_passes_pass_company_uq" ON "legacy_reconciliation_passes" USING btree ("pass_id","company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "legacy_reconciliation_passes_company_completed_idx" ON "legacy_reconciliation_passes" USING btree ("company_id","completed_at");
-- MIG-010 Unit 2.4 (BLOCKER E-2/E-3) Decision #122 / C14 custom security DDL for the
-- reconciliation-pass MARKER (slug `legacy_reconciliation_passes`). drizzle-kit cannot
-- express roles, operation grants, FORCE RLS, or policies, so this entire block is
-- hand-APPENDED to the generated CREATE TABLE above. Every statement is naturally
-- idempotent or guarded/drop-before-create per C14, so a re-apply under the migration
-- advisory lock is a no-op.
--
-- WHAT THIS TABLE IS. One row per Company per COMPLETED reconciliation pass, carrying the
-- DB-clock snapshot instant the pass narrowed its inventory to and the provider-control
-- generation it observed. The canary gate reads the latest such marker and refuses
-- `reconciliation_stale` when there is none, when it is too old, or when the generation has
-- moved (Unit 2.4b). Design `2026-09-01-blocker-e-2-e-3-design.md` §§9.1, 11.4, 12, 13.
--
-- Security matrix — NARROWER than the DEP-003 / JOB-007 / MIG-008 operator-metadata
-- precedents, deliberately:
--   * aoa_operator  SELECT, INSERT  — the operator-authored pass writes markers; the gate
--                                     (also on the operator pool since Unit 1.7) reads them.
--                                     NO UPDATE and NO DELETE: a marker is durable evidence
--                                     of a completed pass, and a pass that can rewrite its
--                                     own marker is not evidence (the §9.2 argument that
--                                     keeps the crosswalk append-only).
--   * aoa_app       NONE            — ★ 0233 / 0239 / 0256 all grant aoa_app SELECT. This one
--                                     does not, because nothing on that pool reads it. The
--                                     BLOCKER E-1 lesson is that the GRANTEE is the boundary,
--                                     so a grant with no reader is authority handed over for
--                                     symmetry. Add it in its own reviewed diff if a
--                                     control-plane reader ever appears.
--   * tenants       NONE            — there is no aoa_app policy at all, so a tenant
--                                     transaction has nothing to match.
--   * FORCE RLS                     — defence in depth against a non-superuser owner mistake
--                                     (E2-F004 rationale).
--
-- `key_generation` is NOT NULL with an explicit `'ungenerationed'` sentinel (design §13).
-- NULL is a NORMAL value for a key generation everywhere else in this system, and the
-- shipped gate treats a NULL as "not superseded" (E7-F005); a nullable marker column would
-- concentrate that hole into one row that disables the staleness check outright.
-- C14 hand-authored security DDL: guarded operator role creation.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aoa_operator') THEN CREATE ROLE "aoa_operator" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE; END IF; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: guarded serving role creation. Created even though it
-- receives no grant here, so the REVOKE below is well-defined on a fresh cluster.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aoa_app') THEN CREATE ROLE "aoa_app" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE; END IF; END $$;
--> statement-breakpoint
-- C14 hand-authored security DDL: remove ambient public authority first.
REVOKE ALL ON "legacy_reconciliation_passes" FROM PUBLIC;
--> statement-breakpoint
-- C14 hand-authored security DDL: strip any inherited aoa_app authority. Unlike 0233/0239/0256
-- there is no re-grant after this one — aoa_app holds NOTHING on the marker.
REVOKE ALL ON "legacy_reconciliation_passes" FROM "aoa_app";
--> statement-breakpoint
-- C14 hand-authored security DDL: strip any inherited aoa_operator authority before the narrow re-grant.
REVOKE ALL ON "legacy_reconciliation_passes" FROM "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: the pass writes markers and the gate reads them. No UPDATE,
-- no DELETE — a marker is durable evidence of a completed pass.
GRANT SELECT, INSERT ON "legacy_reconciliation_passes" TO "aoa_operator";
--> statement-breakpoint
-- C14 hand-authored security DDL: natural idempotent RLS enablement.
ALTER TABLE "legacy_reconciliation_passes" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
-- C14 hand-authored security DDL: FORCE removes a non-superuser owner's exemption.
ALTER TABLE "legacy_reconciliation_passes" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
-- C14 hand-authored security DDL: drop-before-create operator write policy (idempotent replay guard).
DROP POLICY IF EXISTS "legacy_reconciliation_passes_operator_write" ON "legacy_reconciliation_passes";
--> statement-breakpoint
-- C14 hand-authored security DDL: aoa_operator is the only role with any authority on this
-- operator-metadata table. There is deliberately no app-read policy to pair with it.
CREATE POLICY "legacy_reconciliation_passes_operator_write" ON "legacy_reconciliation_passes" TO "aoa_operator"
  USING (true)
  WITH CHECK (true);
