-- SVC-005a - WHO drove a service instance terminal, and it is a FENCE INPUT rather than
-- telemetry.
--
-- E9-F009 recorded the gap and named this half open: `service_instances` carried `status`
-- and `updated_at` and nothing that said WHO moved the row, so a worker that REPORTED itself
-- gone and a control plane that GAVE UP on a worker it could not reach were indistinguishable
-- in durable state. That distinction is load-bearing for the generation rollout fence: only an
-- OBSERVED STOP is a WITNESS that the old generation stopped; everything else leaves E9-F007's
-- window open, where the old worker may still be running and performing external effects.
--
-- ★★★ FOUR AUTHORS AND NOT THREE, AND THE FOURTH IS A P1 FIX. The first revision of this
-- migration had a single `worker_event` author covering every terminal move the ingest
-- applied. External review of PR #415 showed that is a FAIL-OPEN: the daemon emits
-- `service_instance_lost` when `inspect` could not describe the sandbox OR when "a full stop
-- ladder ended with the process still observed `running`"
-- (packages/worker-daemon/src/supervisor/service-lifecycle.ts, whose own comment reads "what is
-- not established is that the PROCESS stopped"). A fenced, authentic, attributed event is
-- evidence of its AUTHORITY, not of its CONTENT -- so treating `lost` as a witness would let
-- the rollout place generation N+1 exactly when generation N's process is KNOWN to have
-- survived cancel and kill. `worker_stopped` and `worker_unconfirmed` keep that distinction in
-- durable state, which is where the fence reads it.
--
-- ONE nullable column and ONE CHECK. Everything below is `db:generate` output apart from the
-- C14 class (a) idempotency guards, which drizzle-kit cannot emit and which this file needs
-- for the same measured reason 0275 and 0278 state: migration-idempotency's static check
-- matches only /^\s*CREATE (UNIQUE )?(TABLE|INDEX)\s+"/, so a bare `ADD COLUMN` is covered by
-- NO static check at all and a re-apply raises 42701, and a bare `ADD CONSTRAINT` raises
-- 42710. No C14 class (b) block is involved: `service_instances` is an already-registered
-- relation whose grants, RLS and policy are in place, and adding a column to it changes no
-- ACL.
--
-- NULLABLE, AND WITH NO DEFAULT, deliberately, and the reason is the same fail-closed one
-- 0278 gives for `last_observed_at`. A DEFAULT would FORGE AN AUTHOR. For a live row NULL
-- means "not terminalized"; for a terminal row it means "terminalized before this column
-- existed", and the fence must read that as UNKNOWN -- which is NOT-A-WITNESS, so an
-- unattributable terminal row STALLS a cross-generation placement rather than admitting it.
-- The fail-closed direction is the whole point of the column.
--
-- NO BACKFILL, and it is safe to omit rather than merely convenient. `service_instances` had
-- ZERO production writers until SVC-002 (0275) and no route could create a service until
-- SVC-007a, so a deployment that has run neither has an EMPTY table; and where rows do exist,
-- NULL is the correct and conservative value for them -- inventing `worker_stopped` for a row
-- nobody witnessed is exactly the forged author this column exists to prevent.
--
-- NO NEW INDEX. The fence's read is per (organization_id, service_id) over that service's
-- instances -- `service_instances_service_idx` on (service_id) plus the organization
-- predicate serves it, and the row count per service is bounded by one live instance plus its
-- terminal history. Re-measure with EXPLAIN when a service has accumulated a long restart
-- history (SVC-004 owns that); the fix would be one db:generate index on
-- (organization_id, service_id, generation).
ALTER TABLE "service_instances" ADD COLUMN IF NOT EXISTS "terminalized_by" text;--> statement-breakpoint
-- The four authors, spelled once in the database. Reconciled against the server-side constant
-- `SERVICE_INSTANCE_TERMINAL_AUTHORS` by an assertion that asserts set EQUALITY, so an author
-- added on one side and not the other is caught rather than silently storable.
DO $$ BEGIN
 ALTER TABLE "service_instances" ADD CONSTRAINT "service_instances_terminalized_by_check" CHECK (terminalized_by IS NULL OR terminalized_by IN ('worker_stopped', 'worker_unconfirmed', 'liveness_deadline', 'control_plane_backstop'));
EXCEPTION
 -- 0275's lesson, applied to a CHECK rather than a FK: catch BOTH codes. A CHECK replay
 -- raises duplicate_object (42710); duplicate_table (42P07) is caught too because catching
 -- only one code is what made 0264 non-idempotent.
 WHEN duplicate_object OR duplicate_table THEN NULL;
END $$;
