// Explicit public exports only (no `export *`) so every wire-surface change is
// visible in review. Runtime values use `export { … }`; type-only aliases use
// `export type { … }` (the root tsconfig sets `isolatedModules: true`).

export { MIN_PROTOCOL_VERSION, PROTOCOL_VERSION, negotiateProtocolVersion } from "./version.js";
export type { ProtocolVersionRange } from "./version.js";

// --- ids.ts: branded identity schemas (runtime values) -----------------------
export {
  organizationIdSchema,
  companyIdSchema,
  agentIdSchema,
  runIdSchema,
  issueIdSchema,
  internalAgentRunIdSchema,
  conversationIdSchema,
  crewRunIdSchema,
  oneShotOperationIdSchema,
  browserRequestIdSchema,
  reconciliationIdSchema,
  jobIdSchema,
  workerIdSchema,
  targetIdSchema,
  leaseIdSchema,
  eventIdSchema,
  artifactIdSchema,
  secretHandleIdSchema,
  serviceIdSchema,
  serviceInstanceIdSchema,
  principalIdSchema,
  sandboxIdSchema,
  attemptNumberSchema,
  eventSequenceSchema,
  fenceTokenSchema,
  sha256DigestSchema,
} from "./ids.js";

// --- ids.ts: inferred identity types -----------------------------------------
export type {
  OrganizationId,
  CompanyId,
  AgentId,
  RunId,
  IssueId,
  InternalAgentRunId,
  ConversationId,
  CrewRunId,
  OneShotOperationId,
  BrowserRequestId,
  ReconciliationId,
  JobId,
  WorkerId,
  TargetId,
  LeaseId,
  EventId,
  ArtifactId,
  SecretHandleId,
  ServiceId,
  ServiceInstanceId,
  PrincipalId,
  SandboxId,
  FenceToken,
  Sha256Digest,
} from "./ids.js";

// --- states.ts: workload/lifecycle constants, schemas, predicates ------------
export {
  WORKLOAD_TYPES,
  workloadTypeSchema,
  JOB_STATUSES,
  jobStatusSchema,
  JOB_TRANSITION_REASONS,
  jobTransitionReasonSchema,
  canTransitionJobStatus,
  ATTEMPT_STATUSES,
  attemptStatusSchema,
  canTransitionAttemptStatus,
  LEASE_STATUSES,
  leaseStatusSchema,
  canTransitionLeaseStatus,
  BROWSER_SESSION_STATUSES,
  browserSessionStatusSchema,
  canTransitionBrowserSessionStatus,
  SERVICE_DESIRED_STATES,
  serviceDesiredStateSchema,
  canTransitionServiceDesiredState,
  SERVICE_INSTANCE_STATUSES,
  serviceInstanceStatusSchema,
  canTransitionServiceInstanceStatus,
} from "./states.js";

// --- states.ts: inferred workload/lifecycle types ----------------------------
export type {
  WorkloadType,
  JobStatus,
  JobTransitionReason,
  AttemptStatus,
  LeaseStatus,
  BrowserSessionStatus,
  ServiceDesiredState,
  ServiceInstanceStatus,
} from "./states.js";

// --- wire-safety.ts: forbidden-key + secret-canary helpers (runtime values) --
export {
  FORBIDDEN_WIRE_KEYS,
  normalizeWireKey,
  findForbiddenWireKeys,
  addForbiddenWireKeyIssues,
  registerSecretCanaries,
  clearRegisteredSecretCanaries,
  getRegisteredSecretCanaries,
  visitWireStrings,
  findSecretCanaryStringMatches,
  createSeededRng,
  generateWireStringSample,
} from "./wire-safety.js";

// --- wire-safety.ts: inferred types ------------------------------------------
export type { WireStringSample } from "./wire-safety.js";

// --- source.ts: principals + execution-source union (runtime values) ---------
export {
  PRINCIPAL_TYPES,
  principalTypeSchema,
  principalV1Schema,
  ONE_SHOT_OPERATION_KINDS,
  oneShotOperationKindSchema,
  EXECUTION_SOURCE_KINDS,
  taskRunSourceSchema,
  commanderTurnSourceSchema,
  crewRunSourceSchema,
  oneShotSourceSchema,
  browserRequestSourceSchema,
  serviceReconcileSourceSchema,
  executionSourceV1Schema,
} from "./source.js";

// --- source.ts: inferred types -----------------------------------------------
export type {
  PrincipalType,
  PrincipalV1,
  OneShotOperationKind,
  ExecutionSourceKind,
  TaskRunSource,
  CommanderTurnSource,
  CrewRunSource,
  OneShotSource,
  BrowserRequestSource,
  ServiceReconcileSource,
  ExecutionSourceV1,
} from "./source.js";

// --- job.ts: placement vocabulary, envelopes, and lease payloads (values) ----
export {
  timestampV1Schema,
  TARGET_CLASSES,
  targetClassSchema,
  TARGET_SCOPES,
  targetScopeSchema,
  TRUST_CLASSES,
  trustClassSchema,
  CREDENTIAL_KINDS,
  credentialKindSchema,
  DATA_LOCALITIES,
  dataLocalitySchema,
  FALLBACK_MODES,
  fallbackModeSchema,
  PLACEMENT_MATRIX,
  isTargetPlacementAllowed,
  providerConstraintRefV1Schema,
  targetRequirementsV1Schema,
  placementV1Schema,
  adapterRefV1Schema,
  workspaceV1Schema,
  batchWorkloadV1Schema,
  browserWorkloadV1Schema,
  serviceWorkloadV1Schema,
  jobEnvelopeV1Schema,
  leaseOfferV1Schema,
  leaseAckV1Schema,
  leaseRenewRequestV1Schema,
  leaseRenewResponseV1Schema,
} from "./job.js";

// --- job.ts: inferred types --------------------------------------------------
export type {
  PlacementMatrixRow,
  TargetClass,
  TargetScope,
  TrustClass,
  CredentialKind,
  DataLocality,
  FallbackMode,
  ProviderConstraintRefV1,
  TargetRequirementsV1,
  PlacementV1,
  AdapterRefV1,
  WorkspaceV1,
  BatchWorkloadV1,
  BrowserWorkloadV1,
  ServiceWorkloadV1,
  JobEnvelopeV1,
  LeaseOfferV1,
  LeaseAckV1,
  LeaseRenewRequestV1,
  LeaseRenewResponseV1,
} from "./job.js";

// --- extensions.ts: the ONE bounded namespaced extension container -----------
export {
  KNOWN_CRITICAL_EXTENSION_NAMESPACES,
  WIRE_EXTENSION_LIMITS,
  wireExtensionSchema,
  wireExtensionsArraySchema,
  addWireExtensionArrayIssues,
} from "./extensions.js";

// --- extensions.ts: inferred types -------------------------------------------
export type { WireExtension } from "./extensions.js";

// --- policy.ts: resource/network/secret/retention/offline contracts (values) -
export {
  resourceLimitsSchema,
  networkAllowRuleSchema,
  networkPolicyV1Schema,
  networkPolicyRefSchema,
  SECRET_MATERIALIZATION_KINDS,
  secretMaterializationSchema,
  SECRET_USE_POLICIES,
  secretUsePolicySchema,
  secretHandleRefSchema,
  ARTIFACT_RETENTION_CLASSES,
  artifactRetentionClassSchema,
  OFFLINE_POLICIES,
  offlinePolicySchema,
} from "./policy.js";

// --- policy.ts: inferred types -----------------------------------------------
export type {
  ResourceLimits,
  NetworkAllowRule,
  NetworkPolicyV1,
  NetworkPolicyRef,
  SecretMaterialization,
  SecretUsePolicy,
  SecretHandleRef,
  ArtifactRetentionClass,
  OfflinePolicy,
} from "./policy.js";

// --- artifacts.ts: workspace/artifact/transfer/commit/quarantine (values) ----
export {
  isSafeWorkspacePath,
  workspacePathSchema,
  expectedAttemptObjectPrefix,
  expectedQuarantineObjectPrefix,
  workspaceBaseV1Schema,
  WORKSPACE_ENTRY_KINDS,
  workspaceEntryKindSchema,
  WORKSPACE_PROVENANCE,
  workspaceProvenanceSchema,
  workspaceEntrySchema,
  workspaceManifestV1Schema,
  PATCH_OPERATION_KINDS,
  patchOperationSchema,
  workspacePatchManifestV1Schema,
  ARTIFACT_KINDS,
  artifactKindSchema,
  RESTRICTED_ARTIFACT_KINDS,
  artifactSensitivitySchema,
  artifactManifestV1Schema,
  artifactTransferGrantRequestV1Schema,
  artifactUploadGrantV1Schema,
  artifactDownloadGrantV1Schema,
  artifactCommitPayloadV1Schema,
  QUARANTINE_REASONS,
  quarantineReasonSchema,
  quarantineGrantPayloadV1Schema,
  quarantineUploadGrantV1Schema,
  quarantineFinalizePayloadV1Schema,
  quarantineUploadReceiptV1Schema,
} from "./artifacts.js";

// --- artifacts.ts: inferred types --------------------------------------------
export type {
  WorkspaceBaseV1,
  WorkspaceEntryKind,
  WorkspaceProvenance,
  WorkspaceEntry,
  WorkspaceManifestV1,
  PatchOperation,
  WorkspacePatchManifestV1,
  ArtifactKind,
  ArtifactSensitivity,
  ArtifactManifestV1,
  ArtifactTransferGrantRequestV1,
  ArtifactUploadGrantV1,
  ArtifactDownloadGrantV1,
  ArtifactCommitPayloadV1,
  QuarantineReason,
  QuarantineGrantPayloadV1,
  QuarantineUploadGrantV1,
  QuarantineFinalizePayloadV1,
  QuarantineUploadReceiptV1,
} from "./artifacts.js";

// --- canonical-json.ts: shared RFC 8785 canonicalizer + digest helpers -------
export {
  CanonicalJsonError,
  canonicalizeJsonV1,
  canonicalEventDigestInputV1,
  verifyWorkerEventDigestV1,
} from "./canonical-json.js";

// --- events.ts: sequenced worker events, batch, and cumulative ACK (values) --
export {
  attemptStartedPayloadV1Schema,
  LOG_STREAMS,
  LOG_LEVELS,
  logPayloadV1Schema,
  progressPayloadV1Schema,
  usagePayloadV1Schema,
  artifactPreparedPayloadV1Schema,
  browserObservationPayloadV1Schema,
  browserApprovalRequestedPayloadV1Schema,
  PERMISSION_TIMEOUT_POLICIES,
  permissionTimeoutPolicySchema,
  PERMISSION_DEFAULT_DECISIONS,
  permissionDefaultDecisionSchema,
  permissionRuntimeDecisionRequestV1Schema,
  WORK_QUESTION_TIMEOUT_POLICIES,
  workQuestionTimeoutPolicySchema,
  workQuestionOptionV1Schema,
  workQuestionRuntimeDecisionRequestV1Schema,
  runtimeDecisionRequestV1Schema,
  serviceInstanceStartedPayloadV1Schema,
  SERVICE_HEALTH_STATUSES,
  serviceHealthPayloadV1Schema,
  serviceCheckpointPreparedPayloadV1Schema,
  serviceCheckpointRestoredPayloadV1Schema,
  serviceGracefulStopObservedPayloadV1Schema,
  serviceInstanceStoppedPayloadV1Schema,
  serviceInstanceLostPayloadV1Schema,
  serviceProviderInterruptedPayloadV1Schema,
  serviceProviderResumedPayloadV1Schema,
  NETWORK_DENIAL_CLASSES,
  networkDeniedPayloadV1Schema,
  TERMINAL_EVENT_STATUSES,
  terminalEventStatusSchema,
  terminalEventPayloadV1Schema,
  WORKER_EVENT_TYPES,
  workerEventTypeSchema,
  workerEventV1Schema,
  workerEventBatchV1Schema,
  WORKER_EVENT_ACK_STATUSES,
  workerEventAckStatusSchema,
  workerEventAckV1Schema,
} from "./events.js";

// --- capabilities.ts: negotiation vocabulary, profiles, and matching (values) -
// `targetRequirementsV1Schema` / `TargetRequirementsV1` are re-exported from the
// job.ts block above (single source of truth) — capabilities.ts imports the same
// object, so they are intentionally NOT re-listed here.
export {
  KNOWN_WORKER_CAPABILITIES,
  workerCapabilitySchema,
  NON_EVENT_DISTRIBUTED_EMISSIONS,
  KNOWN_DISTRIBUTED_EXECUTION_EMISSIONS,
  workerCapacitySchema,
  WORKER_OS,
  WORKER_ARCH,
  workerPlatformSchema,
  providerConstraintProfileRefV1Schema,
  PROVIDER_OPERATIONS,
  providerOperationSchema,
  CORE_PROVIDER_OPERATIONS,
  OPTIONAL_PROVIDER_OPERATIONS,
  CHECKPOINT_MODES,
  HEALTH_MODES,
  providerConstraintProfileV1Schema,
  canonicalProviderConstraintProfileDigestInputV1,
  verifyAndBrandProviderConstraintProfileV1,
  registeredTargetProfileV1Schema,
  workerHelloV1Schema,
  jobCapabilityRequirementsSchema,
  workerSatisfiesRequirements,
} from "./capabilities.js";

// --- capabilities.ts: inferred types -----------------------------------------
export type {
  WorkerCapability,
  WorkerCapacity,
  WorkerPlatform,
  ProviderConstraintProfileRefV1,
  ProviderOperation,
  ProviderConstraintProfileV1,
  VerifiedProviderConstraintProfileV1,
  RegisteredTargetProfileV1,
  WorkerHelloV1,
  JobCapabilityRequirementsV1,
} from "./capabilities.js";

// --- events.ts: inferred types -----------------------------------------------
export type {
  AttemptStartedPayloadV1,
  LogPayloadV1,
  ProgressPayloadV1,
  UsagePayloadV1,
  ArtifactPreparedPayloadV1,
  BrowserObservationPayloadV1,
  BrowserApprovalRequestedPayloadV1,
  PermissionTimeoutPolicy,
  PermissionDefaultDecision,
  PermissionRuntimeDecisionRequestV1,
  WorkQuestionTimeoutPolicy,
  WorkQuestionOptionV1,
  WorkQuestionRuntimeDecisionRequestV1,
  RuntimeDecisionRequestV1,
  ServiceInstanceStartedPayloadV1,
  ServiceHealthPayloadV1,
  ServiceCheckpointPreparedPayloadV1,
  ServiceCheckpointRestoredPayloadV1,
  ServiceGracefulStopObservedPayloadV1,
  ServiceInstanceStoppedPayloadV1,
  ServiceInstanceLostPayloadV1,
  ServiceProviderInterruptedPayloadV1,
  ServiceProviderResumedPayloadV1,
  NetworkDeniedPayloadV1,
  TerminalEventStatus,
  TerminalEventPayloadV1,
  WorkerEventType,
  WorkerEventV1,
  WorkerEventBatchV1,
  WorkerEventAckStatus,
  WorkerEventAckV1,
} from "./events.js";

// --- errors.ts: stable protocol error vocabulary (runtime values) ------------
export {
  PROTOCOL_ERROR_CODES,
  protocolErrorCodeSchema,
  RETRYABLE_PROTOCOL_ERROR_CODES,
  isRetryableProtocolErrorCode,
  isKnownProtocolErrorCode,
  PROTOCOL_ERROR_DETAIL_LIMITS,
  protocolErrorV1Schema,
} from "./errors.js";

// --- errors.ts: inferred types -----------------------------------------------
export type { ProtocolErrorCode, ProtocolErrorV1 } from "./errors.js";

// --- transport.ts: framework-neutral operation/control wrappers (values) -----
export {
  AUTH_AUDIENCES,
  authAudienceSchema,
  enrollmentRequestV1Schema,
  enrollmentResponseV1Schema,
  pollRequestV1Schema,
  POLL_RESPONSE_OUTCOMES,
  pollResponseV1Schema,
  leaseAckOperationRequestV1Schema,
  leaseAckOperationResponseV1Schema,
  leaseRenewOperationRequestV1Schema,
  leaseRenewOperationResponseV1Schema,
  eventUploadOperationRequestV1Schema,
  eventUploadOperationResponseV1Schema,
  artifactTransferGrantOperationRequestV1Schema,
  ARTIFACT_TRANSFER_GRANT_OUTCOMES,
  artifactTransferGrantOperationResponseV1Schema,
  isTransferGrantResponsePairedV1,
  artifactCommitOperationRequestV1Schema,
  ARTIFACT_COMMIT_OUTCOMES,
  artifactCommitOperationResponseV1Schema,
  quarantineGrantOperationRequestV1Schema,
  quarantineGrantOperationResponseV1Schema,
  quarantineFinalizeOperationRequestV1Schema,
  quarantineFinalizeOperationResponseV1Schema,
  PRODUCT_APPROVAL_DECISIONS,
  productApprovalDecisionSchema,
  governedActionRefSchema,
  productApprovalResultV1Schema,
  productApprovalAuthorizesActionV1,
  PERMISSION_DECISIONS,
  permissionDecisionSchema,
  WORK_QUESTION_OUTCOMES,
  workQuestionOutcomeSchema,
  permissionRuntimeDecisionResultV1Schema,
  workQuestionRuntimeDecisionResultV1Schema,
  runtimeDecisionResultV1Schema,
  RUNTIME_DECISION_MATCH_REASONS,
  matchRuntimeDecisionResultToRequestV1,
  CONTROL_COMMAND_KINDS,
  controlCommandV1Schema,
  CONTROL_ACK_STATUSES,
  controlCommandAckStatusSchema,
  controlCommandAckV1Schema,
  CONTROL_RECEIVER_DECISIONS,
  controlReceiverDecisionSchema,
  decideControlReceiverV1,
  EVENT_RECEIVER_DECISIONS,
  eventReceiverDecisionSchema,
  decideEventReceiverV1,
  WORKER_PROTOCOL_OPERATIONS,
  OPERATION_DESCRIPTORS,
} from "./transport.js";

// --- transport.ts: inferred types --------------------------------------------
export type {
  AuthAudience,
  EnrollmentRequestV1,
  EnrollmentResponseV1,
  PollRequestV1,
  PollResponseV1,
  LeaseAckOperationRequestV1,
  LeaseAckOperationResponseV1,
  LeaseRenewOperationRequestV1,
  LeaseRenewOperationResponseV1,
  EventUploadOperationRequestV1,
  EventUploadOperationResponseV1,
  ArtifactTransferGrantOperationRequestV1,
  ArtifactTransferGrantOperationResponseV1,
  ArtifactCommitOperationRequestV1,
  ArtifactCommitOperationResponseV1,
  QuarantineGrantOperationRequestV1,
  QuarantineGrantOperationResponseV1,
  QuarantineFinalizeOperationRequestV1,
  QuarantineFinalizeOperationResponseV1,
  ProductApprovalDecision,
  GovernedActionRefV1,
  ProductApprovalResultV1,
  PermissionDecision,
  WorkQuestionOutcome,
  PermissionRuntimeDecisionResultV1,
  WorkQuestionRuntimeDecisionResultV1,
  RuntimeDecisionResultV1,
  RuntimeDecisionMatchReason,
  RuntimeDecisionMatchResultV1,
  ControlCommandV1,
  ControlCommandAckStatus,
  ControlCommandAckV1,
  ControlReceiverStateV1,
  ControlReceiverCommandV1,
  ControlReceiverDecisionV1,
  EventReceiverStateV1,
  EventReceiverInputV1,
  EventReceiverDecisionV1,
  WorkerProtocolOperation,
  OperationRetryRule,
  OperationDescriptorV1,
} from "./transport.js";
