export {
  COMPANY_STATUSES,
  DEPLOYMENT_MODES,
  DEPLOYMENT_EXPOSURES,
  AUTH_BASE_URL_MODES,
  AGENT_STATUSES,
  AGENT_ADAPTER_TYPES,
  AGENT_ROLES,
  AGENT_ROLE_LABELS,
  displayAgentRole,
  AGENT_ICON_NAMES,
  ISSUE_STATUSES,
  ISSUE_PRIORITIES,
  ISSUE_WORK_MODES,
  ISSUE_SOURCES,
  AGENT_COMPLETION_POLICIES,
  AGENT_COMPLETION_POLICY_SOURCES,
  ISSUE_REVIEWER_SOURCES,
  GOAL_LEVELS,
  GOAL_STATUSES,
  PROJECT_TYPES,
  PROJECT_STATUSES,
  PROJECT_COLORS,
  APPROVAL_TYPES,
  CREATABLE_APPROVAL_TYPES,
  APPROVAL_STATUSES,
  SECRET_PROVIDERS,
  SECRET_PROVIDER_CONFIG_STATUSES,
  SECRET_PROVIDER_CONFIG_HEALTH_STATUSES,
  SECRET_STATUSES,
  SECRET_MANAGED_MODES,
  SECRET_VERSION_STATUSES,
  SECRET_BINDING_TARGET_TYPES,
  SECRET_RESOLUTION_SCOPES,
  SECRET_ACCESS_OUTCOMES,
  RUNTIME_PROVIDER_KEY_PROVIDERS,
  RUNTIME_PROVIDER_KEY_STATUSES,
  STORAGE_PROVIDERS,
  HEARTBEAT_INVOCATION_SOURCES,
  HEARTBEAT_RUN_STATUSES,
  RUN_LIVENESS_STATES,
  ISSUE_MONITOR_STATUSES,
  ISSUE_MONITOR_CLEAR_REASONS,
  WAKEUP_TRIGGER_DETAILS,
  WAKEUP_REQUEST_STATUSES,
  LIVE_EVENT_TYPES,
  PRINCIPAL_TYPES,
  MEMBERSHIP_STATUSES,
  ORGANIZATION_STATUSES,
  ORGANIZATION_ROLES,
  ORGANIZATION_INVITATION_STATUSES,
  DEFAULT_ORGANIZATION_ID,
  DEFAULT_ORGANIZATION_SLUG,
  INSTANCE_USER_ROLES,
  INVITE_TYPES,
  INVITE_JOIN_TYPES,
  JOIN_REQUEST_TYPES,
  JOIN_REQUEST_STATUSES,
  JOIN_REQUEST_APPROVAL_SOURCES,
  ENVIRONMENT_DRIVERS,
  ENVIRONMENT_STATUSES,
  ENVIRONMENT_LEASE_STATUSES,
  ENVIRONMENT_LEASE_POLICIES,
  ENVIRONMENT_LEASE_CLEANUP_STATUSES,
  // Phase 5 execution-target registry (Task 1) — these were added to
  // constants.ts by Task 1 but never re-exported through this barrel; fixed
  // here because Task 10/13 need them via "@armyofagents/shared".
  EXECUTION_TARGET_KINDS,
  EXECUTION_TARGET_TRUST_CLASSES,
  EXECUTION_TARGET_STATUSES,
  WORKER_CONTROL_HEADERS,
  ORG_MAX_CONCURRENT_RUNS_DEFAULT,
  ORG_MAX_CONCURRENT_RUNS_MAX,
  type ExecutionTargetKind,
  type ExecutionTargetTrustClass,
  type ExecutionTargetStatus,
  MEMORY_ITEM_CATEGORIES,
  MEMORY_ITEM_SOURCES,
  MEMORY_ITEM_STATUSES,
  MEMORY_ITEM_LAYERS,
  MEMORY_ITEM_VISIBILITY,
  // Memory infrastructure
  MEMORY_RELATION_KINDS,
  MEMORY_RETRIEVAL_TRIGGERS,
  MEMORY_EXTRACTION_INPUT_TYPES,
  MEMORY_EXTRACTION_STATUSES,
  MEMORY_EXTRACTION_BATCH_STATUSES,
  MCP_ACTOR_TYPES,
  MEMORY_RECALL_BUDGETS,
  MEMORY_RECALL_BUDGET_LIMITS,
  MEMORY_SCOPE_FILTERS,
  MEMORY_WRITE_SCOPES,
  COMPANY_BRAIN_NODE_TYPES,
  COMPANY_BRAIN_EDGE_KINDS,
  COMPANY_BRAIN_EDGE_SOURCE_CLASSES,
  COMPANY_BRAIN_EDGE_EDITABILITY,
  COMPANY_BRAIN_DERIVED_EDGE_KINDS,
  COMPANY_BRAIN_APPEND_ONLY_EDGE_KINDS,
  COMPANY_BRAIN_EDITABLE_EDGE_KINDS,
  COMPANY_BRAIN_EDGE_EDITABILITY_BY_KIND,
  type MemoryRelationKind,
  type MemoryRetrievalTrigger,
  type MemoryExtractionInputType,
  type MemoryExtractionStatus,
  type MemoryExtractionBatchStatus,
  type McpActorType,
  type MemoryRecallBudget,
  type MemoryScopeFilter,
  type MemoryWriteScope,
  type CompanyBrainNodeType,
  type CompanyBrainEdgeKind,
  type CompanyBrainEdgeSourceClass,
  type CompanyBrainEdgeEditability,
  USER_ROLES,
  ROLE_RANK,
  roleAtLeast,
  PERMISSION_KEYS,
  ARTIFACT_TYPES,
  ARTIFACT_STATUSES,
  ARTIFACT_VERSION_SOURCES,
  SUGGESTION_CATEGORIES,
  SUGGESTION_STATUSES,
  SUGGESTION_ACTION_TYPES,
  MEMORY_FEEDBACK_PATTERN_TYPES,
  MEMORY_FEEDBACK_PATTERN_STATUSES,
  MEMORY_ITEM_VERSION_STATUSES,
  SEARCH_ENTITY_TYPES,
  DETECTED_OUTPUT_STATUSES,
  DETECTED_OUTPUT_SOURCES,
  BRIEF_ITEM_TYPES,
  BRIEF_ITEM_STATUSES,
  BRIEF_STATUSES,
  BRIEF_DEDUP_ACTIONS,
  type DetectedOutputStatus,
  type DetectedOutputSource,
  type MemoryItemCategory,
  type MemoryItemSource,
  type MemoryItemStatus,
  type MemoryItemLayer,
  type MemoryItemVisibility,
  type ArtifactType,
  type ArtifactStatus,
  type ArtifactVersionSource,
  type SuggestionCategory,
  type SuggestionStatus,
  type SuggestionActionType,
  type MemoryFeedbackPatternType,
  type MemoryFeedbackPatternStatus,
  type MemoryItemVersionStatus,
  type SearchEntityType,
  type UserRole,
  type CompanyStatus,
  type DeploymentMode,
  type DeploymentExposure,
  type AuthBaseUrlMode,
  type AgentStatus,
  type AgentAdapterType,
  type AgentRole,
  type AgentIconName,
  type IssueStatus,
  type IssuePriority,
  type IssueWorkMode,
  type IssueSource,
  type AgentCompletionPolicy,
  type AgentCompletionPolicySource,
  type IssueReviewerSource,
  type GoalLevel,
  type GoalStatus,
  type ProjectType,
  type ProjectStatus,
  type ApprovalType,
  type CreatableApprovalType,
  type ApprovalStatus,
  type SecretProvider,
  type SecretProviderConfigStatus,
  type SecretProviderConfigHealthStatus,
  type SecretStatus,
  type SecretManagedMode,
  type SecretVersionStatus,
  type SecretBindingTargetType,
  type SecretResolutionScope,
  type SecretAccessOutcome,
  type RuntimeProviderKeyProvider,
  type RuntimeProviderKeyStatus,
  type StorageProvider,
  type HeartbeatInvocationSource,
  type HeartbeatRunStatus,
  type RunLivenessState,
  type IssueMonitorStatus,
  type IssueMonitorClearReason,
  type WakeupTriggerDetail,
  type WakeupRequestStatus,
  type LiveEventType,
  type PrincipalType,
  type MembershipStatus,
  type OrganizationStatus,
  type OrganizationRole,
  type OrganizationInvitationStatus,
  type InstanceUserRole,
  type InviteType,
  type InviteJoinType,
  type JoinRequestType,
  type JoinRequestStatus,
  type JoinRequestApprovalSource,
  type EnvironmentDriver,
  type EnvironmentStatus,
  type EnvironmentLeaseStatus,
  type EnvironmentLeasePolicy,
  type EnvironmentLeaseCleanupStatus,
  type PermissionKey,
  type BriefItemType,
  type BriefItemStatus,
  type BriefStatus,
  type BriefDedupAction,
  type ThreadScopeVersionStatus,
  type ThreadScopeItemKind,
  type ThreadScopeItemStatus,
  type ThreadAgentActionType,
  type ThreadAgentActionStatus,
  type ThreadDerivedStage,
  // Discussions
  DISCUSSION_STATUSES,
  DISCUSSION_SCOPE_TYPES,
  DISCUSSION_ENTRY_INPUT_TYPES,
  EXTRACTION_STATUSES,
  EXTRACTION_ITEM_TYPES,
  EXTRACTION_ITEM_STATUSES,
  // Threads (extends Discussions)
  THREAD_ORIGIN_SOURCES,
  THREAD_ORIGIN_MEDIA,
  THREAD_INTENTS,
  THREAD_PHASES,
  THREAD_SCOPE_VERSION_STATUSES,
  THREAD_SCOPE_ITEM_KINDS,
  THREAD_SCOPE_ITEM_STATUSES,
  THREAD_AGENT_ACTION_TYPES,
  THREAD_AGENT_ACTION_STATUSES,
  THREAD_DERIVED_STAGES,
  THREAD_VISIBILITIES,
  THREAD_SUBTYPES,
  THREAD_PARTICIPANT_PRINCIPAL_TYPES,
  THREAD_PARTICIPANT_ROLES,
  THREAD_LINK_KINDS,
  THREAD_ROUTER_DECISIONS,
  THREAD_INBOX_STATUSES,
  // Internal Agent
  AGENT_CAPABILITIES,
  AGENT_EXECUTION_MODES,
  AGENT_PROVIDERS,
  AGENT_MODELS_BY_PROVIDER,
  CLI_TOOLS,
  NOTIFICATION_PREFERENCES,
  TRIGGER_TYPES,
  TRIGGER_SOURCES,
  IA_RUN_STATUSES,
  IA_MESSAGE_ROLES,
  IA_CONVERSATION_STATUSES,
  REMINDER_STATUSES,
  NOTIFICATION_TYPES,
  SKILL_CUSTOMIZED_ERROR_CODE,
  SKILL_NAME_TAKEN_ERROR_CODE,
  COMMANDER_TOOL_PERMISSION_DEFAULT,
  COMMANDER_RUNTIME_APPROVAL_STATUSES,
  COMMANDER_RUNTIME_APPROVAL_DECISIONS,
  COMMANDER_TOOL_TRUST_SCOPES,
  type CommanderToolPermission,
  type CommanderToolPermissions,
  type CommanderRuntimeApprovalStatus,
  type CommanderRuntimeApprovalDecision,
  type CommanderToolTrustScope,
  // Discussion types
  type DiscussionStatus,
  type DiscussionScopeType,
  type DiscussionEntryInputType,
  type ExtractionStatus,
  type ExtractionItemType,
  type ExtractionItemStatus,
  // Thread types
  type ThreadOriginSource,
  type ThreadOriginMedium,
  type ThreadIntent,
  type ThreadPhase,
  type ThreadVisibility,
  type ThreadSubtype,
  type ThreadParticipantPrincipalType,
  type ThreadParticipantRole,
  type ThreadLinkKind,
  type ThreadRouterDecision,
  type ThreadInboxStatus,
  type AgentCapability,
  type AgentExecutionMode,
  type AgentProvider,
  type NotificationPreference,
  type TriggerType,
  type TriggerSource,
  type IaRunStatus,
  type IaMessageRole,
  type IaConversationStatus,
  type ReminderStatus,
  type NotificationType,
  ISSUE_ORIGIN_KINDS,
  RECOVERY_ORIGIN_KINDS,
  ROUTINE_STATUSES,
  ROUTINE_CONCURRENCY_POLICIES,
  ROUTINE_CATCH_UP_POLICIES,
  ROUTINE_TRIGGER_KINDS,
  ROUTINE_TRIGGER_SIGNING_MODES,
  ROUTINE_RUN_STATUSES,
  ROUTINE_RUN_SOURCES,
  ROUTINE_VARIABLE_TYPES,
  type IssueOriginKind,
  type RoutineStatus,
  type RoutineConcurrencyPolicy,
  type RoutineCatchUpPolicy,
  type RoutineTriggerKind,
  type RoutineTriggerSigningMode,
  type RoutineRunStatus,
  type RoutineRunSource,
  type RoutineVariableType,
  // Plugin system
  PLUGIN_API_VERSION,
  PLUGIN_STATUSES,
  PLUGIN_WORKER_BLOCKED_IN_CLOUD_REASON,
  PLUGIN_STATUS_REASON_CODES,
  PLUGIN_CATEGORIES,
  PLUGIN_CAPABILITIES,
  PLUGIN_TRUST_TIERS,
  CAPABILITY_DESCRIPTIONS,
  PLUGIN_UI_SLOT_TYPES,
  PLUGIN_UI_SLOT_ENTITY_TYPES,
  PLUGIN_STATE_SCOPE_KINDS,
  PLUGIN_LAUNCHER_PLACEMENT_ZONES,
  PLUGIN_LAUNCHER_ACTIONS,
  PLUGIN_LAUNCHER_BOUNDS,
  PLUGIN_LAUNCHER_RENDER_ENVIRONMENTS,
  PLUGIN_EVENT_TYPES,
  PLUGIN_JOB_STATUSES,
  PLUGIN_JOB_RUN_STATUSES,
  PLUGIN_JOB_RUN_TRIGGERS,
  PLUGIN_WEBHOOK_DELIVERY_STATUSES,
  type PluginStatus,
  type PluginStatusReasonCode,
  type PluginCategory,
  type PluginCapability,
  type PluginTrustTier,
  type PluginUiSlotType,
  type PluginUiSlotEntityType,
  type PluginStateScopeKind,
  type PluginLauncherPlacementZone,
  type PluginLauncherAction,
  type PluginLauncherBounds,
  type PluginLauncherRenderEnvironment,
  type PluginEventType,
  type PluginJobStatus,
  type PluginJobRunStatus,
  type PluginJobRunTrigger,
  type PluginWebhookDeliveryStatus,
  PLUGIN_BRIDGE_ERROR_CODES,
  type PluginBridgeErrorCode,
  DEPARTMENT_FUNCTION_TYPES,
  type DepartmentFunctionType,
  COMPOSER_MAX_ATTACHMENTS,
  COMPOSER_MAX_ATTACHMENT_BYTES,
  COMPOSER_ATTACHMENT_CONTENT_TYPES,
} from "./constants.js";

export {
  CREW_PROVIDERS,
  COMMANDER_PROVIDERS,
  providerToCliTool,
  providerToCrewAdapter,
  cliToolToProvider,
} from "./provider-mapping.js";
export type { CrewProvider, CommanderProvider, CliTool, CrewAdapterType } from "./provider-mapping.js";

export type {
  Organization,
  OrganizationMembership,
  OrganizationInvitation,
} from "./types/organization.js";
export {
  createOrganizationSchema,
  inviteToOrganizationSchema,
  type CreateOrganization,
  type InviteToOrganization,
} from "./validators/organization.js";

export type {
  Company,
  Agent,
  AgentPermissions,
  AgentKeyCreated,
  AgentConfigRevision,
  AdapterEnvironmentCheckLevel,
  AdapterEnvironmentTestStatus,
  AdapterEnvironmentCheck,
  AdapterEnvironmentTestResult,
  AgentInstructionsBundleMode,
  AgentInstructionsFileSummary,
  AgentInstructionsFileDetail,
  AgentInstructionsBundle,
  AssetImage,
  Project,
  ProjectGoalRef,
  ProjectWorkspace,
  Issue,
  IssueAssigneeAdapterOverrides,
  IssueComment,
  IssueCommentAuthorType,
  IssueCommentMetadata,
  IssueCommentPresentation,
  IssueMonitor,
  IssueMonitorPolicy,
  IssueAttachment,
  IssueLabel,
  IssueDocumentSummary,
  IssueDocument,
  DocumentRevision,
  Goal,
  MemoryItem,
  MemoryIndexStatus,
  CompanyBrainNodeRef,
  CompanyBrainNode,
  CompanyBrainEdge,
  CompanyBrainSemanticEdgeRecord,
  CompanyBrainNeighborsResponse,
  CompanyBrainOverviewResponse,
  CompanyBrainMemoryUsageAgent,
  CompanyBrainMemoryUsageResponse,
  MemoryAssetRecord,
  MemoryAssetCreateInput,
  MemoryAssetUpdateInput,
  MemoryFolderRecord,
  MemoryFolderCreateInput,
  MemoryFolderUpdateInput,
  Artifact,
  ArtifactVersion,
  ArtifactWithVersions,
  Notification,
  TaskOutput,
  TaskOutputType,
  TaskOutputStatus,
  TaskOutputReviewState,
  HealthCategory,
  HealthFinding,
  HealthFindingAction,
  HealthReport,
  HealthReportSummary,
  HealthScope,
  HealthSeverity,
  HealthStatus,
  MemoryItemVersion,
  PendingMemoryVersionReview,
  PendingMemoryArchiveReview,
  PendingMemoryQueue,
  Suggestion,
  MemoryFeedbackPattern,
  AgentTrustScore,
  UserRoleAssignment,
  McpApiKey,
  McpApiKeyCreated,
  McpClientConnection,
  McpStatus,
  GlobalSearchEntityType,
  GlobalSearchResult,
  GlobalSearchGroup,
  GlobalSearchResponse,
  Approval,
  ApprovalComment,
  CostEvent,
  CostSummary,
  CostByAgent,
  HeartbeatRun,
  HeartbeatRunEvent,
  AgentRuntimeState,
  AgentTaskSession,
  AgentWakeupRequest,
  InstanceSchedulerHeartbeatAgent,
  DetectedOutput,
  DetectedOutputForUI,
  LiveEvent,
  HubItemChangedLivePayload,
  HubCountsChangedLivePayload,
  HubDigestChangedLivePayload,
  DashboardSummary,
  HomeSummary,
  GoalProgress,
  GoalGapNudge,
  RecentActivityItem,
  SetupStatus,
  ActivityActorType,
  ActivityEvent,
  SidebarBadges,
  CompanyMembership,
  PrincipalPermissionGrant,
  Invite,
  JoinRequest,
  InstanceUserRoleGrant,
  AccessUserProfile,
  AdminUserDirectoryEntry,
  UserCompanyAccessEntry,
  UserCompanyAccessResponse,
  HumanSocialLinkType,
  HumanSocialLink,
  CompanyUserProfile,
  TeamPermissionSummary,
  TeamCurrentUserSummary,
  TeamMemberSummary,
  TeamInviteSummary,
  TeamSummary,
  HumanWorkloadTaskSummary,
  HumanWorkloadManagedAgent,
  HumanWorkloadManagedAgentTask,
  HumanWorkloadAttentionItem,
  HumanWorkloadSummary,
  HumanWorkload,
  UnifiedOrgNode,
  CompanyPortabilityInclude,
  CompanyPortabilitySecretRequirement,
  CompanyPortabilityCompanyManifestEntry,
  CompanyPortabilityAgentManifestEntry,
  CompanyPortabilityManifest,
  CompanyPortabilityExportResult,
  CompanyPortabilityExportPreviewCounts,
  CompanyPortabilityExportPreviewResult,
  CompanyPortabilitySource,
  CompanyPortabilityImportTarget,
  CompanyPortabilityAgentSelection,
  CompanyPortabilityCollisionStrategy,
  CompanyPortabilityPreviewRequest,
  CompanyPortabilityPreviewAgentPlan,
  CompanyPortabilityPreviewProjectPlan,
  CompanyPortabilityPreviewIssuePlan,
  CompanyPortabilityProjectManifestEntry,
  CompanyPortabilityProjectType,
  CompanyPortabilityIssueManifestEntry,
  CompanyPortabilitySkillManifestEntry,
  CompanyPortabilitySkillFileInventoryEntry,
  CompanyPortabilityPreviewSkillPlan,
  CompanyPortabilityRoutineManifestEntry,
  CompanyPortabilityRoutineTriggerManifestEntry,
  CompanyPortabilityRoutineVariableManifestEntry,
  CompanyPortabilityEnvInputManifestEntry,
  CompanyPortabilityEnvInputKind,
  CompanyPortabilityEnvInputRequirement,
  CompanyPortabilityEnvInputPortability,
  CompanyPortabilityInternalAgentConfigManifestEntry,
  CompanyPortabilityBudgetPolicyManifestEntry,
  CompanyPortabilityBudgetPolicyScopeType,
  CompanyPortabilityCostEventManifestEntry,
  CompanyPortabilityCostEventsInclude,
  CompanyPortabilityCostEventsDateRange,
  CompanyPortabilityFinanceEventManifestEntry,
  CompanyPortabilityFinanceEventDirection,
  CompanyPortabilityQuotaWindowManifestEntry,
  CompanyPortabilityWorkflowTemplateManifestEntry,
  CompanyPortabilityPreviewRoutinePlan,
  CompanyPortabilityPreviewResult,
  CompanyPortabilityImportRequest,
  CompanyPortabilityImportResult,
  CompanyPortabilityExportRequest,
  ImportWarning,
  ImportWarningKind,
  EnvBinding,
  AgentEnvConfig,
  CompanySecret,
  SecretProviderDescriptor,
  CompanySecretProviderConfig,
  SecretProviderConfigHealthResponse,
  CompanySecretBinding,
  CompanySecretUsageBinding,
  SecretAccessEvent,
  RemoteSecretImportCandidate,
  RemoteSecretImportPreviewResult,
  RemoteSecretImportResult,
  RuntimeProviderKey,
  CompanySkillSourceType,
  CompanySkillTrustLevel,
  CompanySkillCompatibility,
  CompanySkillSourceBadge,
  CompanySkillFileInventoryEntry,
  CompanySkill,
  CompanySkillListItem,
  CompanySkillDetail,
  CompanySkillUsageAgent,
  CompanySkillUpdateStatus,
  CompanySkillImportRequest,
  CompanySkillImportResult,
  CompanySkillRefusedImport,
  CompanySkillProjectScanRequest,
  CompanySkillProjectScanResult,
  CompanySkillProjectScanSkipped,
  CompanySkillProjectScanConflict,
  CompanySkillCreateRequest,
  CompanySkillFileDetail,
  CompanySkillFileUpdateRequest,
  CompanySkillImportPackageRequest,
  BudgetPolicy,
  BudgetPolicySummary,
  BudgetIncident,
  BudgetOverview,
  UpsertBudgetPolicyInput,
  ResolveBudgetIncidentInput,
  AddMemberInput,
  TransferAdminInput,
  MemberDependencies,
  ReassignAndRemoveInput,
  Routine,
  RoutineTrigger,
  RoutineRun,
  RoutineTriggerSecretMaterial,
  RoutineDetail,
  RoutineRunSummary,
  RoutineListItem,
  RoutineVariable,
  RoutineVariableDefaultValue,
  RoutineSnapshot,
  RoutineRevision,
  RoutineRevisionListItem,
  InstanceGeneralSettings,
  InstanceExperimentalSettings,
  InstanceSettings,
  BackupRetentionPolicy,
  BackupRetentionTieredPolicy,
  BackupRetentionCountPolicy,
  FeedbackDataSharingPreference,
  FeedbackExportSummary,
  FeedbackTargetType,
  FeedbackTraceTargetSummary,
  FeedbackVoteValue,
  FeedbackVote,
  FeedbackVoteSummary,
  ExecutionWorkspaceStrategyType,
  ProjectExecutionWorkspaceDefaultMode,
  ExecutionWorkspaceMode,
  ExecutionWorkspaceProviderType,
  ExecutionWorkspaceStatus,
  ExecutionWorkspaceStrategy,
  ProjectExecutionWorkspacePolicy,
  IssueExecutionWorkspaceSettings,
  ExecutionWorkspace,
  ExecutionWorkspaceSummary,
  WorkspaceRuntimeService,
  ExecutionWorkspaceCloseReadinessState,
  ExecutionWorkspaceCloseActionKind,
  ExecutionWorkspaceCloseAction,
  ExecutionWorkspaceCloseLinkedIssue,
  ExecutionWorkspaceCloseGitReadiness,
  ExecutionWorkspaceCloseReadiness,
  ExecutionWorkspaceConfig,
  WorkspaceRuntimeDesiredState,
  WorkspaceRuntimeServiceStateMap,
  ProjectWorkspaceRuntimeConfig,
  WorkspaceRuntimeControlTarget,
  WorkspaceOperationPhase,
  WorkspaceOperationStatus,
  WorkspaceOperation,
  GitHubPrCreateRequest,
  GitHubPrCreateResponse,
  GitHubPrMetadata,
  GitHubPrSyncMetadata,
  GitHubPrSyncResponse,
  GitHubRepoCollaborator,
  GitHubRepoLabel,
  GitHubRepoMilestone,
  GitHubRepoBranch,
  GitHubAuthorizedRepo,
  GitHubPrMergeMethod,
  GitHubPrMergeRequest,
  GitHubPrActionResponse,
  GitHubAppStatus,
  GitHubAuthStatus,
  // Git Command Centre
  GitPrReviewState,
  GitCIStatus,
  GitPipelineStage,
  GitBranchInfo,
  GitCommitNode,
  GitGraphData,
  GitProjectGraphResponse,
  GitBranchEnrichment,
  GitProjectEnrichResponse,
  // Plugin system
  JsonSchema,
  PluginJobDeclaration,
  PluginWebhookDeclaration,
  PluginToolDeclaration,
  PluginUiSlotDeclaration,
  PluginLauncherActionDeclaration,
  PluginLauncherRenderDeclaration,
  PluginLauncherRenderContextSnapshot,
  PluginLauncherDeclaration,
  PluginMinimumHostVersion,
  PluginUiDeclaration,
  PaperclipPluginManifestV1,
  PluginRecord,
  PluginStateRecord,
  PluginConfig,
  PluginEntityQuery,
  PluginEntityRecord,
  PluginJobRecord,
  PluginJobRunRecord,
  PluginWebhookDeliveryRecord,
  HumanCapabilityDocumentKind,
  HumanCapabilityDocumentTemplate,
  HumanCapabilityDocumentSummary,
  HumanCapabilityDocumentDetail,
  HumanCapabilityBundle,
  HumanContextIdentity,
  HumanContextAuthority,
  HumanContextResponsibility,
  HumanContextCapabilityDocument,
  HumanContextBundle,
  HumanSearchMatchedField,
  SearchHumansInput,
  HumanSearchMatchSnippet,
  HumanSearchResult,
  HumanSearchResponse,
  HumanContextResolutionMode,
  HumanContextResolutionResult,
  InstallPlugin,
  UpdatePluginStatus,
  UpsertPluginConfig,
  PatchPluginConfig,
  SetPluginState,
  ListPluginState,
  Environment,
  EnvironmentLease,
  EnvironmentProbeCheck,
  EnvironmentProbeResult,
} from "./types/index.js";

export {
  DAILY_RETENTION_PRESETS,
  WEEKLY_RETENTION_PRESETS,
  MONTHLY_RETENTION_PRESETS,
  DEFAULT_BACKUP_RETENTION,
  FEEDBACK_DATA_SHARING_PREFERENCES,
  DEFAULT_FEEDBACK_DATA_SHARING_PREFERENCE,
  FEEDBACK_TARGET_TYPES,
  FEEDBACK_VOTE_VALUES,
} from "./types/index.js";

export {
  createCompanySchema,
  updateCompanySchema,
  type CreateCompany,
  type UpdateCompany,
  createAgentSchema,
  createAgentHireSchema,
  updateAgentSchema,
  adapterModelFamilyMismatch,
  isShellSafeModelId,
  updateAgentInstructionsPathSchema,
  updateAgentInstructionsBundleSchema,
  upsertAgentInstructionsFileSchema,
  createAgentKeySchema,
  wakeAgentSchema,
  resetAgentSessionSchema,
  testAdapterEnvironmentSchema,
  agentPermissionsSchema,
  updateAgentPermissionsSchema,
  type CreateAgent,
  type CreateAgentHire,
  type UpdateAgent,
  type UpdateAgentInstructionsPath,
  type UpdateAgentInstructionsBundle,
  type UpsertAgentInstructionsFile,
  type CreateAgentKey,
  type WakeAgent,
  type ResetAgentSession,
  type TestAdapterEnvironment,
  type UpdateAgentPermissions,
  createProjectSchema,
  updateProjectSchema,
  createProjectWorkspaceSchema,
  updateProjectWorkspaceSchema,
  type CreateProject,
  type UpdateProject,
  type CreateProjectWorkspace,
  type UpdateProjectWorkspace,
  createIssueSchema,
  createIssueLabelSchema,
  updateIssueSchema,
  checkoutIssueSchema,
  addIssueCommentSchema,
  linkIssueApprovalSchema,
  createIssueAttachmentMetadataSchema,
  type CreateIssue,
  type CreateIssueLabel,
  type UpdateIssue,
  type CheckoutIssue,
  type AddIssueComment,
  type LinkIssueApproval,
  type CreateIssueAttachmentMetadata,
  createGoalSchema,
  updateGoalSchema,
  type CreateGoal,
  type UpdateGoal,
  submitBraindumpSchema,
  BRAINDUMP_CONTENT_MAX_LENGTH,
  type SubmitBraindump,
  createMemoryItemSchema,
  updateMemoryItemSchema,
  suggestMemoryUpdateSchema,
  suggestMemoryArchiveSchema,
  type CreateMemoryItem,
  type UpdateMemoryItem,
  type SuggestMemoryUpdate,
  type SuggestMemoryArchive,
  // Memory infrastructure validators
  memoryProfileSchema,
  memoryWriteCapabilitiesSchema,
  createMemoryRelationSchema,
  memoryRetrievalRowSchema,
  memoryExtractionProgressSchema,
  createMemoryExtractionSchema,
  createMemoryExtractionBatchSchema,
  type MemoryProfile,
  type MemoryWriteCapabilities,
  type CreateMemoryRelation,
  type MemoryRetrievalRow,
  type MemoryExtractionProgress,
  type CreateMemoryExtraction,
  type CreateMemoryExtractionBatch,
  companyBrainNodeRefSchema,
  companyBrainNodeSchema,
  companyBrainEdgeSchema,
  companyBrainNeighborQuerySchema,
  companyBrainNeighborsResponseSchema,
  companyBrainOverviewQuerySchema,
  companyBrainOverviewResponseSchema,
  createCompanyBrainSemanticEdgeSchema,
  updateCompanyBrainSemanticEdgeSchema,
  type CompanyBrainNodeRefInput,
  type CompanyBrainNodeInput,
  type CompanyBrainEdgeInput,
  type CompanyBrainNeighborQuery,
  type CompanyBrainNeighborsResponseInput,
  type CompanyBrainOverviewQuery,
  type CompanyBrainOverviewResponseInput,
  type CreateCompanyBrainSemanticEdge,
  type UpdateCompanyBrainSemanticEdge,
  // Phase 6.0: memory folders + assets
  memoryFolderCreateSchema,
  memoryFolderUpdateSchema,
  normalizeMemoryFolderPath,
  memoryAssetUpdateSchema,
  memoryAssetMoveSchema,
  createDebriefSchema,
  updateDebriefSchema,
  mcpDebriefSchema,
  type CreateDebrief,
  type UpdateDebrief,
  type McpDebrief,
  updateBriefSchema,
  createBriefItemSchema,
  updateBriefItemSchema,
  approveBriefSchema,
  type UpdateBrief,
  type CreateBriefItem,
  type UpdateBriefItem,
  type ApproveBrief,
  createApprovalSchema,
  resolveApprovalSchema,
  requestApprovalRevisionSchema,
  resubmitApprovalSchema,
  addApprovalCommentSchema,
  type CreateApproval,
  type ResolveApproval,
  type RequestApprovalRevision,
  type ResubmitApproval,
  type AddApprovalComment,
  envBindingPlainSchema,
  envBindingSecretRefSchema,
  envBindingSchema,
  envConfigSchema,
  readEnvBindingValue,
  createSecretSchema,
  rotateSecretSchema,
  updateSecretSchema,
  secretProviderConfigPayloadSchema,
  createSecretProviderConfigSchema,
  updateSecretProviderConfigSchema,
  createSecretBindingSchema,
  createRuntimeProviderKeySchema,
  remoteSecretImportPreviewSchema,
  remoteSecretImportCommitSchema,
  updateRuntimeProviderKeySchema,
  createRuntimeProviderKeyWithSecretSchema,
  type CreateSecret,
  type RotateSecret,
  type UpdateSecret,
  type CreateSecretProviderConfig,
  type UpdateSecretProviderConfig,
  type CreateSecretBinding,
  type RemoteSecretImportPreview,
  type RemoteSecretImportCommit,
  type CreateRuntimeProviderKey,
  type UpdateRuntimeProviderKey,
  type CreateRuntimeProviderKeyWithSecret,
  createCostEventSchema,
  updateBudgetSchema,
  financeDirectionSchema,
  createFinanceEventSchema,
  financeDateRangeQuerySchema,
  financeListQuerySchema,
  type CreateFinanceEvent,
  type FinanceListQuery,
  createMcpApiKeySchema,
  updateMcpSettingsSchema,
  createAssetImageMetadataSchema,
  createCompanyInviteSchema,
  acceptInviteSchema,
  listJoinRequestsQuerySchema,
  claimJoinRequestApiKeySchema,
  updateMemberPermissionsSchema,
  updateUserCompanyAccessSchema,
  searchAdminUsersQuerySchema,
  boardCliAuthAccessLevelSchema,
  createCliAuthChallengeSchema,
  resolveCliAuthChallengeSchema,
  updateTeamMemberRoleSchema,
  type CreateCostEvent,
  type UpdateBudget,
  type CreateMcpApiKey,
  type UpdateMcpSettings,
  type CreateAssetImageMetadata,
  type CreateCompanyInvite,
  type AcceptInvite,
  type ListJoinRequestsQuery,
  type ClaimJoinRequestApiKey,
  type UpdateMemberPermissions,
  type UpdateUserCompanyAccess,
  type SearchAdminUsersQuery,
  type UpdateTeamMemberRole,
  portabilityIncludeSchema,
  portabilitySecretRequirementSchema,
  portabilityCompanyManifestEntrySchema,
  portabilityAgentManifestEntrySchema,
  portabilityProjectManifestEntrySchema,
  portabilitySkillManifestEntrySchema,
  portabilitySkillFileInventoryEntrySchema,
  portabilityInternalAgentConfigManifestSchema,
  portabilityBudgetPolicyManifestSchema,
  portabilityFinanceEventManifestSchema,
  portabilityQuotaWindowManifestSchema,
  portabilityWorkflowTemplateManifestSchema,
  portabilityManifestSchema,
  portabilitySourceSchema,
  portabilityTargetSchema,
  portabilityAgentSelectionSchema,
  portabilityCollisionStrategySchema,
  companyPortabilityExportSchema,
  companyPortabilityPreviewSchema,
  companyPortabilityImportSchema,
  type CompanyPortabilityExport,
  type CompanyPortabilityPreview,
  type CompanyPortabilityImport,
  createArtifactSchema,
  updateArtifactSchema,
  createArtifactVersionSchema,
  mcpArtifactVersionSchema,
  mcpArtifactVersionShape,
  type CreateArtifact,
  type UpdateArtifact,
  type CreateArtifactVersion,
  type McpArtifactVersion,
  taskOutputTypeSchema,
  taskOutputStatusSchema,
  taskOutputReviewStateSchema,
  upsertTaskOutputSchema,
  mutableTaskOutputSchema,
  type UpsertTaskOutput,
  type MutableTaskOutput,
  confirmDetectedOutputSchema,
  type ConfirmDetectedOutput,
  createAssetFileMetadataSchema,
  type CreateAssetFileMetadata,
  createDiscussionSchema,
  createDiscussionEntrySchema,
  updateDiscussionSchema,
  approveItemsSchema,
  createAnnotationSchema,
  type CreateDiscussion,
  type CreateDiscussionEntry,
  type UpdateDiscussion,
  type ApproveItems,
  type CreateAnnotation,
  updateInternalAgentConfigSchema,
  commanderContextScopeSchema,
  commanderContextSurfaceSchema,
  chatMessageSchema,
  type UpdateInternalAgentConfig,
  type CommanderContextScope,
  type ChatMessage,
  workflowStepSchema,
  workflowDependencySchema,
  createWorkflowTemplateSchema,
  updateWorkflowTemplateSchema,
  type CreateWorkflowTemplate,
  type UpdateWorkflowTemplate,
  companySkillSourceTypeSchema,
  companySkillTrustLevelSchema,
  companySkillCompatibilitySchema,
  companySkillSourceBadgeSchema,
  companySkillFileInventoryEntrySchema,
  companySkillSchema,
  companySkillListItemSchema,
  companySkillUsageAgentSchema,
  companySkillDetailSchema,
  companySkillUpdateStatusSchema,
  companySkillImportSchema,
  companySkillProjectScanRequestSchema,
  companySkillProjectScanSkippedSchema,
  companySkillProjectScanConflictSchema,
  companySkillProjectScanResultSchema,
  companySkillCreateSchema,
  companySkillFileDetailSchema,
  companySkillFileUpdateSchema,
  companySkillImportPackageSchema,
  type CompanySkillImport,
  type CompanySkillProjectScan,
  type CompanySkillCreate,
  type CompanySkillFileUpdate,
  upsertBudgetPolicySchema,
  resolveBudgetIncidentSchema,
  type UpsertBudgetPolicy,
  type ResolveBudgetIncident,
  issueDocumentKeySchema,
  issueDocumentFormatSchema,
  upsertIssueDocumentSchema,
  ISSUE_DOCUMENT_FORMATS,
  type UpsertIssueDocument,
  addMemberSchema,
  transferAdminSchema,
  reassignAndRemoveSchema,
  STANDARD_HUMAN_CAPABILITY_DOCUMENTS,
  humanSocialLinkSchema,
  createHumanCapabilityDocumentSchema,
  updateHumanCapabilityDocumentSchema,
  updateCompanyUserProfileSchema,
  searchHumansSchema,
  type AddMember,
  type TransferAdmin,
  type ReassignAndRemove,
  type UpdateCompanyUserProfile,
  type CreateHumanCapabilityDocument,
  type UpdateHumanCapabilityDocument,
  type SearchHumans,
  routineVariableSchema,
  createRoutineSchema,
  updateRoutineSchema,
  createRoutineTriggerSchema,
  updateRoutineTriggerSchema,
  runRoutineSchema,
  rotateRoutineTriggerSecretSchema,
  restoreRoutineRevisionSchema,
  type CreateRoutine,
  type UpdateRoutine,
  type CreateRoutineTrigger,
  type UpdateRoutineTrigger,
  type RunRoutine,
  type RestoreRoutineRevision,
  instanceGeneralSettingsSchema,
  patchInstanceGeneralSettingsSchema,
  instanceExperimentalSettingsSchema,
  patchInstanceExperimentalSettingsSchema,
  backupRetentionPolicySchema,
  feedbackDataSharingPreferenceSchema,
  feedbackTargetTypeSchema,
  feedbackVoteValueSchema,
  upsertIssueFeedbackVoteSchema,
  type UpsertIssueFeedbackVote,
  type PatchInstanceGeneralSettings,
  type PatchInstanceExperimentalSettings,
  executionWorkspaceStatusSchema,
  executionWorkspaceConfigSchema,
  workspaceRuntimeControlTargetSchema,
  executionWorkspaceCloseReadinessStateSchema,
  executionWorkspaceCloseActionKindSchema,
  executionWorkspaceCloseActionSchema,
  executionWorkspaceCloseLinkedIssueSchema,
  executionWorkspaceCloseGitReadinessSchema,
  workspaceRuntimeServiceSchema,
  executionWorkspaceCloseReadinessSchema,
  updateExecutionWorkspaceSchema,
  type UpdateExecutionWorkspace,
  pluginManifestV1Schema,
  type PluginManifestV1Input,
  currentUserProfileSchema,
  updateCurrentUserProfileSchema,
  type CurrentUserProfile,
  type UpdateCurrentUserProfile,
  sidebarPreferencesSchema,
  updateSidebarPreferencesSchema,
  type SidebarPreferences,
  type UpdateSidebarPreferences,
  DEFAULT_UNIVERSE_PREFERENCES,
  UNIVERSE_PREFERENCE_SECTIONS,
  resolveUniversePreferences,
  universePreferencesSchema,
  universePreferencePatchSchema,
  universePreferenceResetSchema,
  type UniversePreferences,
  type UniversePreferenceOverrides,
  type PreferenceSection,
  type UniversePreferencesSnapshot,
  type UniversePreferencePatchInput,
  type UniversePreferenceResetInput,
  homeBoardLayoutItemSchema,
  homeBoardLayoutArraySchema,
  updateHomeBoardLayoutSchema,
  validateHomeBoardLayout,
  type HomeBoardLayoutItemInput,
  type HomeBoardLayoutItemLike,
  type HomeBoardLayoutValidationResult,
  type UpdateHomeBoardLayout,
  UNIVERSE_REF_KINDS,
  UNIVERSE_LAYOUT_SCHEMA_VERSION,
  UNIVERSE_LAYOUT_MAX_PANELS,
  UNIVERSE_LAYOUT_MAX_OPERATIONS,
  UNIVERSE_LAYOUT_COORD_LIMIT,
  UNIVERSE_LAYOUT_MIN_DIMENSION,
  UNIVERSE_LAYOUT_MAX_DIMENSION,
  UNIVERSE_LAYOUT_MIN_ZOOM,
  UNIVERSE_LAYOUT_MAX_ZOOM,
  rectSchema,
  layoutOpSchema,
  layoutPatchSchema,
  universeLayoutDocumentSchema,
  emptyUniverseLayoutDocument,
  type UniverseRefKind,
  type Rect,
  type LayoutOp,
  type LayoutPatch,
  type LayoutAck,
  type UniverseLayoutDocument,
  UNIVERSE_DRAFT_DESTINATION_KINDS,
  UNIVERSE_DRAFT_SCHEMA_VERSION,
  UNIVERSE_DRAFT_MAX_TEXT,
  UNIVERSE_DRAFT_MAX_ATTACHMENTS,
  draftDestinationSchema,
  draftPatchSchema,
  universeDraftPayloadSchema,
  pendingDraftAttemptSchema,
  structuredDraftPatchSchema,
  universeDraftPatchSchema,
  type UniverseDraftDestinationKind,
  type UniverseDraftDestination,
  type UniverseDraftPatch,
  type UniverseDraftPayload,
  type PendingDraftAttempt,
  type UniverseDraftPatchInput,
  type UniverseDraft,
  INBOX_DISMISSAL_ITEM_KEY_REGEX,
  inboxDismissalSchema,
  createInboxDismissalSchema,
  type InboxDismissal,
  type CreateInboxDismissal,
  isGitHubRepoUrl,
  createUserEntityPinSchema,
  type CreateUserEntityPin,
  createUserNoteSchema,
  updateUserNoteSchema,
  userNoteColorSchema,
  type CreateUserNote,
  type UpdateUserNote,
  listHubItemsQuery,
  hubActionSchema,
  hubUserStateSchema,
  hubBulkActionSchema,
  hubUndoSchema,
  hubPreferencesSchema,
  updateHubPreferencesSchema,
  hubAutopilotPolicySchema,
  updateHubAutopilotPolicySchema,
  hubAutopilotEvaluationResultSchema,
  hubAutopilotActionsResponseSchema,
  hubListRowSchema,
  hubListResponseSchema,
  hubCurationMetadataSchema,
  runtimeDecisionAnswerSchema,
  runtimeDecisionDetailSchema,
  type ListHubItemsQuery,
  type HubActionInput,
  type HubUserStateInput,
  type HubBulkActionInput,
  type HubUndoInput,
  type HubPreferences,
  type UpdateHubPreferencesInput,
  type HubAutopilotRule,
  type HubAutopilotPolicy,
  type UpdateHubAutopilotPolicyInput,
  type HubAutopilotEvaluationResult,
  type HubAutopilotActionRow,
  type HubAutopilotActionsResponse,
  type HubListRow,
  type HubListResponse,
  type HubCurationMetadata,
  type RuntimeDecisionAnswerInput,
  type RuntimeDecisionDetail,
  createEnvironmentSchema,
  e2bEnvironmentConfigSchema,
  environmentDriverSchema,
  environmentLeaseCleanupStatusSchema,
  environmentLeasePolicySchema,
  environmentLeaseStatusSchema,
  environmentStatusSchema,
  probeEnvironmentSchema,
  updateEnvironmentSchema,
  type CreateEnvironmentInput,
  type E2bEnvironmentConfig,
  type ProbeEnvironmentInput,
  type UpdateEnvironmentInput,
  // Phase 5 execution-target registry (Task 5/13) — see the matching note in
  // validators/index.ts.
  dockerIsolationSchema,
  gvisorEnvironmentConfigSchema,
  createExecutionTargetSchema,
  workerExecutionTargetHeartbeatSchema,
  issueWorkerEnrollmentCodeSchema,
  type CreateExecutionTargetInput,
  type WorkerExecutionTargetHeartbeatInput,
  type IssueWorkerEnrollmentCodeInput,
} from "./validators/index.js";

export {
  GITHUB_PAT_SECRET_NAME,
  GITHUB_PAT_ACTIVITY_KINDS,
  type GitHubPatActivityKind,
} from "./constants/github.js";

export { API_PREFIX, API } from "./api.js";
export * from "./notification-preferences.js";

// Phase 3b/3c/3d: Commander cockpit data contract
export type {
  CockpitTaskItem,
  CockpitTaskResponsibilityReason,
  CockpitTaskResponsibility,
  CockpitWorkTaskItem,
  CockpitTaskGroup,
  CockpitActiveWork,
  CockpitAwaitingReview,
  CockpitSliceStatus,
  CockpitSliceMeta,
  CockpitMeta,
  CockpitTaskBucket,
  CockpitTaskBucketResponse,
  CockpitCounts,
  CockpitRunItem,
  CockpitReminderItem,
  CockpitNoteItem,
  CockpitInboxItem,
  CockpitDiscussionItem,
  CockpitData,
  CockpitApprovalSource,
  CockpitApprovalItem,
  CockpitPinnedEntityType,
  CockpitPinnedItem,
  CockpitGoalsAtRiskItem,
  CockpitBudgetPulseItem,
  CockpitDoneTodayItem,
  CockpitProactiveItem,
  CockpitTeammatesActivityItem,
} from "./cockpit.js";

export {
  COCKPIT_PRESENTATION_VERSION,
  COCKPIT_ATTENTION_FILTERS,
  COCKPIT_SECTION_IDS,
  COCKPIT_RELATIONSHIPS,
  COCKPIT_GROUP_IDS,
  COCKPIT_ATTENTION_KINDS,
  commanderOpenTargetSchema,
  cockpitAttentionSignalSchema,
  cockpitPresentationItemSchema,
  cockpitPresentationSchema,
  classifyCockpitRelationship,
  createCockpitAttentionSignal,
  matchesCockpitAttentionFilter,
  type CockpitAttentionFilter,
  type CockpitSectionId,
  type CockpitRelationship,
  type CockpitGroupId,
  type CockpitAttentionKind,
  type CockpitAttentionCategory,
  type CockpitAttentionTone,
  type CockpitEntityRef,
  type CommanderAnchor,
  type CommanderViewerTabDescriptor,
  type CommanderOpenTarget,
  type CockpitAttentionSignal,
  type CockpitLinkedAction,
  type CockpitPresentationItem,
  type CockpitGroup,
  type CockpitPresentationSection,
  type CockpitPresentationMeta,
  type CockpitPresentation,
  type CockpitRelationshipInput,
} from "./cockpit-presentation.js";

// Marketplace catalog types
export {
  CATALOG_SCHEMA_VERSION_MIN,
  CATALOG_SCHEMA_VERSION_MAX,
  MarketplaceCategorySchema,
  MarketplaceTagSchema,
  MarketplaceTrustTierSchema,
  MarketplaceItemTypeSchema,
  MarketplaceProviderRefSchema,
  MarketplaceSkillBundleSchema,
  MarketplaceSkillFrontmatterSchema,
  MarketplaceSkillMetadataSchema,
  MarketplaceCatalogItemSchema,
  MarketplaceCatalogFileSchema,
  MarketplacePackageSchema,
  MarketplaceMaintenanceStageSchema,
  MarketplaceReconciliationOperationIdSchema,
  MarketplaceReconcileRequestSchema,
  MarketplaceReconcileSkipCategorySchema,
  MarketplaceReconcileDiagnosticCodeSchema,
  MarketplaceOperationDiagnosticCodeSchema,
  MarketplaceReconcileFailureCodeSchema,
  MarketplaceReconcileErrorCodeSchema,
  MarketplaceRecoveryCodeSchema,
  MarketplaceRetryInstructionSchema,
  MarketplaceReconcileSkipSchema,
  MarketplaceReconcileFailureSchema,
  MarketplaceReconcileDiagnosticSchema,
  MarketplaceReconcileResponseSchema,
  MarketplaceReconcileErrorResponseSchema,
  MarketplaceReconciliationInspectionSchema,
  MARKETPLACE_RECOVERY,
  MARKETPLACE_RECOVERY_DOC_URL,
  parseMarketplaceCatalog,
  isSchemaVersionSupported,
  MARKETPLACE_SETTINGS_DEFAULTS,
  type MarketplaceCategory,
  type MarketplaceTag,
  type MarketplaceTrustTier,
  type MarketplaceItemType,
  type MarketplaceProviderRef,
  type MarketplaceSkillBundle,
  type MarketplaceSkillFrontmatter,
  type MarketplaceSkillMetadata,
  type MarketplaceCatalogItem,
  type CatalogItem,
  type MarketplaceCatalogFile,
  type CatalogSyncStatus,
  type MarketplaceMaintenanceStage,
  type MarketplaceReconcileRequest,
  type MarketplaceReconcileSkipCategory,
  type MarketplaceReconcileDiagnosticCode,
  type MarketplaceOperationDiagnosticCode,
  type MarketplaceReconcileFailureCode,
  type MarketplaceReconcileErrorCode,
  type MarketplaceRecoveryCode,
  type MarketplaceRetryInstruction,
  type MarketplaceReconcileSkip,
  type MarketplaceReconcileFailure,
  type MarketplaceReconcileDiagnostic,
  type MarketplaceReconcileResponse,
  type MarketplaceReconcileErrorResponse,
  type MarketplaceReconciliationInspection,
  type MarketplaceSettings,
  type PendingUpdateStatus,
  type PendingUpdateType,
  type PendingUpdate,
  type MarketplacePackage,
} from "./marketplace.js";
export {
  ROUTINE_VARIABLE_NAME_PATTERN,
  ROUTINE_VARIABLE_MATCHER,
  BUILTIN_ROUTINE_VARIABLE_NAMES,
  isBuiltinRoutineVariable,
  getBuiltinRoutineVariableValues,
  isValidRoutineVariableName,
  extractRoutineVariableNames,
  syncRoutineVariablesWithTemplate,
  stringifyRoutineVariableValue,
  interpolateRoutineTemplate,
} from "./routine-variables.js";
export { normalizeAgentUrlKey, deriveAgentUrlKey, isUuidLike } from "./agent-url-key.js";
export { deriveProjectUrlKey, normalizeProjectUrlKey } from "./project-url-key.js";
export {
  PROJECT_MENTION_SCHEME,
  buildProjectMentionHref,
  parseProjectMentionHref,
  extractProjectMentionIds,
  type ParsedProjectMention,
  SKILL_MENTION_SCHEME,
  buildSkillMentionHref,
  parseSkillMentionHref,
  extractSkillMentionIds,
  normalizeSkillSlug,
  type ParsedSkillMention,
} from "./project-mentions.js";

export {
  SENSITIVE_ENV_KEY,
  SENSITIVE_ENV_VALUE_PATTERNS,
  looksLikeSecretValue,
  shouldRedactSecretValue,
  redactEnvForLogs,
} from "./redaction.js";

export {
  paperclipConfigSchema,
  configMetaSchema,
  llmConfigSchema,
  databaseBackupConfigSchema,
  databaseConfigSchema,
  loggingConfigSchema,
  serverConfigSchema,
  authConfigSchema,
  secretsConfigSchema,
  storageConfigSchema,
  storageLocalDiskConfigSchema,
  storageS3ConfigSchema,
  secretsLocalEncryptedConfigSchema,
  type AoaConfig,
  type LlmConfig,
  type DatabaseBackupConfig,
  type DatabaseConfig,
  type LoggingConfig,
  type ServerConfig,
  type AuthConfig,
  type StorageConfig,
  type StorageLocalDiskConfig,
  type StorageS3Config,
  type SecretsConfig,
  type SecretsLocalEncryptedConfig,
  type ConfigMeta,
} from "./config-schema.js";

export * from "./teams.js";
export * from "./home-board.js";
export * from "./composer-contracts.js";
export * from "./autonomy-levels.js";
export * from "./inbound-routing.js";
export * from "./user-notes.js";
export * from "./commander-output-refs.js";
export * from "./viewer-show-ref.js";
export * from "./viewer-control.js";
export * from "./safe-browser-url.js";
export * from "./commander-input-refs.js";
export * from "./hub.js";
export * from "./work-questions.js";
export * from "./user-entity-follows.js";
export * from "./notification-registry.js";
export * from "./types/job-control.js";
export * from "./job-control-source.js";
export {
  submitJobCommandSchema,
  submitJobSourceSchema,
  type SubmitJobCommandInput,
} from "./validators/job-control.js";

// ── API contract artifacts ──
// Phase 1 thread coordination contract: shared by backend (Lane A) and UI (Lane B).
// DISCUSSION_ENTRY_INPUT_TYPES_V2 was consolidated into the canonical
// DISCUSSION_ENTRY_INPUT_TYPES constant in Task A3 (same pattern A2 used for
// THREAD_VISIBILITIES_V2). Import the canonical constant from the package root.
export {
  DiscussionEntryAttachmentSchema,
  DiscussionEntryV2Schema,
  ProposedTaskSchema,
  ScopeProposalPayloadSchema,
  ThreadVisibilitySchema,
  AdapterConfigEntrySchema,
  CommanderAdapterConfigSchema,
  CrewAdapterConfigSchema,
  NewNotificationTypeSchema,
  NEW_NOTIFICATION_TYPES,
  type DiscussionEntryAttachment,
  type DiscussionEntryV2,
  type ProposedTask,
  type ScopeProposalPayload,
  type AdapterConfigEntry,
  type CommanderAdapterConfig,
  type CrewAdapterConfig,
  type NewNotificationType,
} from "./api/threads-contract.js";
export {
  ONBOARDING_JOURNEYS,
  ONBOARDING_STATES,
  FOUNDER_PHASE1_STATES,
  INVITED_PHASE1_STATES,
  orderedStatesFor,
  FIRST_RUN_PERSONAS,
  normalizeLegacyOnboardingState,
  type OnboardingJourney,
  type OnboardingState,
  type PendingInvitation,
  type PostAuthJourneyResult,
  type FirstRunPersona,
} from "./onboarding.js";

// Provider readiness (Provider Readiness initiative)
export { PROBE_OUTCOMES, NON_BLOCKING_PROBE_OUTCOMES, isNonBlockingProbeOutcome } from "./probe-outcome.js";
export type { ProbeOutcome, NonBlockingProbeOutcome } from "./probe-outcome.js";
export {
  ADAPTER_PROBE_RETRY_AFTER_SECONDS,
  ADAPTER_PROBE_BUSY_ERROR,
  PROVIDER_READINESS_STALE_MS,
  isReadinessStale,
} from "./adapter-probe.js";
export * from "./providers/provider-catalog.js";
export * from "./mcp-connector-catalog.js";
export * from "./provider-connections.js";
export * from "./notification-delivery.js";

export { checkpointDataSchema, checkpointPatchSchema, type CheckpointData, type CheckpointPatch, type CheckpointSnapshot } from "./validators/universe-layout.js";
export {
  universeAttentionSourceRefSchema,
  universeAttentionEntrySchema,
  universeAttentionResponseSchema,
  universeAttentionCheckpointInputSchema,
  universeAttentionCheckpointSchema,
  type UniverseAttentionSourceRef,
  type UniverseAttentionEntry,
  type UniverseAttentionResponse,
  type UniverseAttentionCheckpointInput,
  type UniverseAttentionCheckpoint,
} from "./validators/universe-attention.js";
export {
  universeSnapshotReferenceSchema,
  universeSnapshotTaskSchema,
  universeSnapshotOutputSchema,
  universeReconciliationSnapshotSchema,
  type UniverseReconciliationSnapshot,
} from "./validators/universe-reconciliation.js";
export {
  universeIntakeDestinationSchema,
  beginUniverseIntakeSchema,
  universeIntakeSnapshotSchema,
  type UniverseIntakeDestination,
  type BeginUniverseIntake,
  type UniverseIntakeSnapshot,
} from "./validators/universe-intake.js";
export {
  FORMAT_DISPOSITIONS,
  FORMAT_FAILURES,
  formatCapabilitySchema,
  type FormatDisposition,
  type FormatCapability,
  type FormatFailure,
} from "./validators/universe-formats.js";
export * from "./types/universe-context.js";
export { universeReferenceSchema, universeViewportSchema, universeContextSchema, type UniverseContextInput } from "./validators/universe-context.js";
